function display_blogs()
{

document.getElementById("social").innerHTML="<h3>Find me:</h3>    <a href=\"https://www.facebook.com/matt.lao1\">      <img src=\"../icons/facebook.png\" width =\"50px\"></a>    <a href=\"https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile\">      <img src=\"../icons/linked.png\" width =\"50px\"></a><br>    <a href=\"https://github.com/laomatt\">      <img src=\"../icons/github.png\" width =\"50px\"></a>    <a href=\"https://plus.google.com/u/0/115046235123468150722/posts\">      <img src=\"../icons/Google.png\" width =\"50px\"></a><br>    <a href=\"https://twitter.com/LaoMatt\">      <img src=\"../icons/twitter.png\" width =\"50px\"></a>    <a href=\"http://www.quora.com/Matt-Lao-1\">      <img src=\"../icons/quora.png\" width =\"50px\"</a><br>      <a href=\"https://www.youtube.com/channel/UCEKPDwTITT16mD4ARJWFAIQ\">        <img src=\"../icons/youtube.png\" width =\"50px\"></a>    <a href=\"http://stackoverflow.com/users/4135830/matt-lao\">      <img src=\"../icons/stackoverflow.png\" width =\"50px\"</a><br>"




document.getElementById("blog_list").innerHTML="<h3>Browse blogs</h3><div id=\"tech_blog_entries_list\">  <p><h4>Tech</h4></p>        <div class=\"blog_menu_item\">        <a href=\"t7-JavaScript.html\">Javascript vs. Ruby</a>        <div class=\"date\"> Febuary 7th, 2015</div>      </div><br>      <div class=\"blog_menu_item\">        <a href=\"t6-oop-concepts.html\">Object orientated concepts</a>        <div class=\"date\"> January 29th, 2015</div>      </div><br>      <div class=\"blog_menu_item\">        <a href=\"t5-ruby-classes.html\">Ruby classes</a>        <div class=\"date\"> January 17th, 2015</div>      </div><br>      <div class=\"blog_menu_item\">        <a href=\"t4-enumerable-methods.html\">Enumerable methods</a>        <div class=\"date\"> January 2nd, 2015</div>      </div><br>        <div class=\"blog_menu_item\">        <a href=\"t3-arrays-hashes.html\">Arrays vs. Hashes</a>        <div class=\"date\"> December 22nd, 2014</div>      </div><br>      <div class=\"blog_menu_item\">        <a href=\"t2-css-design.html\">CSS design</a>        <div class=\"date\"> December 17th, 2014</div>      </div><br>      <div class=\"blog_menu_item\">        <a href=\"t1-git-blog.html\">Git and Github</a>        <div class=\"date\"> December 10th, 2014</div>      </div><br></div><div id=\"cult_blog_entries_list\">  <p><h4>Cult</h4></p>      <div class=\"blog_menu_item\">        <a href=\"c7-values.html\">Values</a>        <div class=\"date\"> Febuary 7th, 2015</div>      </div><br>      <div class=\"blog_menu_item\">        <a href=\"c6-stereotype-threat.html\">Stereotype threat</a>        <div class=\"date\"> January 29th, 2015</div>      </div><br>      <div class=\"blog_menu_item\">        <a href=\"c5-feedback.html\">Feedback cycle</a>        <div class=\"date\"> January 15th, 2015</div>      </div><br>      <div class=\"blog_menu_item\">        <a href=\"c4-tech-issues.html\">Issues in the industry</a>        <div class=\"date\"> January 2nd, 2015</div>      </div><br>      <div class=\"blog_menu_item\">        <a href=\"c3_thinking-style.html\">My thinking style</a>        <div class=\"date\"> Dec 25, 2014</div>      </div><br>     <div class=\"blog_menu_item\">        <a href=\"c1-chefs-kitchen.html\">Chefs kitchen</a>        <div class=\"date\"> Dec 10, 2014</div>      </div><br></div>"


}

function shake_item()
{
  document.getElementById("social").style.top
}


function show_social(){
document.getElementById("social_main").innerHTML="<h3>Find me:</h3>    <a href=\"https://www.facebook.com/matt.lao1\">      <img src=\"icons/facebook.png\" width =\"50px\"></a>    <a href=\"https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile\">      <img src=\"icons/linked.png\" width =\"50px\"></a><br>    <a href=\"https://github.com/laomatt\">      <img src=\"icons/github.png\" width =\"50px\"></a>    <a href=\"https://plus.google.com/u/0/115046235123468150722/posts\">      <img src=\"icons/Google.png\" width =\"50px\"></a><br>    <a href=\"https://twitter.com/LaoMatt\">      <img src=\"icons/twitter.png\" width =\"50px\"></a>    <a href=\"http://www.quora.com/Matt-Lao-1\">      <img src=\"icons/quora.png\" width =\"50px\"</a><br>      <a href=\"https://www.youtube.com/channel/UCEKPDwTITT16mD4ARJWFAIQ\">        <img src=\"icons/youtube.png\" width =\"50px\"></a>    <a href=\"http://stackoverflow.com/users/4135830/matt-lao\">      <img src=\"icons/stackoverflow.png\" width =\"50px\"</a><br>"
}