# text="
# hut cam soy bull nun coy soy gel peg cafe cease hug pear peer adultery app bog bee bulk bean butt bull bracket breed cum deter determined dull doll donkey dolly eradicate earie fort faulty frog froggy faggot fag gasoline gall bladder
# "

text="AS A NEWLYWED LESBIAN COUPLE IN TEXAS CELEBRATE DEFYING A STATEWIDE BAN ON GAY MARRIAGE, THE STATE'S REPUBLICAN ATTORNEY GENERAL IS PREPARING TO TELL A COURT FRIDAY WHY IT SHOULD RULE THEIR NUPTIALS ARE INVALID.

THE MARRIAGE LICENSE GIVEN TO TWO AUSTIN WOMEN — WHO SUCCEEDED BY SEIZING ON A RULING THIS WEEK IN AN UNRELATED ESTATE SQUABBLE — THRUST TEXAS BACK INTO THE NATIONAL SPOTLIGHT OVER GAY MARRIAGE BUT DIDN'T SEND SAME-SEX COUPLES RUSHING TO COURTHOUSES.

THE TEXAS SUPREME COURT ACTED QUICKLY AFTER AN APPEAL FROM ATTORNEY GENERAL KEN PAXTON TO BLOCK OTHER POTENTIAL GAY MARRIAGES, MAKING THE NUPTIALS SOMEWHAT BITTERSWEET FOR SUZANNE BRYANT AND SARAH GOODFRIEND.

\"WE JUST FEEL LIKE WE WERE IN THE RIGHT PLACE AT THE RIGHT TIME, TO MAYBE PUT A NICE CRACK IN THAT DOOR THAT'S GOING TO OPEN UP FOR ALL TEXANS,\" BRYANT SAID. TEXAS IS ONE OF 13 STATES WHERE GAY MARRIAGE REMAINS OUTLAWED.

RELATED

 SARAH GOODFRIEND, LEFT, AND SUZANNE BRYANT CELEBRATE WITH THEIR DAUGHTERS DAWN GOODFRIEND, LEFT, 18, AND TING GOODFRIEND, 13, AT HIGHLAND LOUNGE IN AUSTIN, TEXAS, ON THURSDAY, FEB. 19, 2015, AFTER BECOMING THE FIRST LEGALLY MARRIED SAME-SEX COUPLE IN TEXAS.
SARAH GOODFRIEND, LEFT, AND SUZANNE BRYANT CELEBRATE WITH THEIR DAUGHTERS DAWN GOODFRIEND, LEFT, 18, AND TING GOODFRIEND, 13, AT HIGHLAND LOUNGE IN AUSTIN, TEXAS, ON THURSDAY, FEB. 19, 2015, AFTER BECOMING THE FIRST LEGALLY MARRIED SAME-SEX COUPLE IN TEXAS. | AUSTIN AMERICAN-STATESMAN, JAY JANNER AP PHOTO

›‹
FRIENDS AND DEMOCRATIC LAWMAKERS TOASTED BRYANT AND GOODFRIEND, WHO HAVE BEEN TOGETHER 30 YEARS AND HAVE TWO TEENAGE DAUGHTERS, AT A DOWNTOWN AUSTIN BAR TUESDAY NIGHT AFTER COUNTY OFFICIALS OBEYED A JUDICIAL ORDER TO WED THE COUPLE.

GOODFRIEND, 58, HAS OVARIAN CANCER. A STATE DISTRICT JUDGE RAISED THE \"SEVERITY AND UNCERTAINTY\" OF HER CONDITION IN GRANTING THE WOMEN PERMISSION TO MARRY, SENDING THE COUPLE SCRAMBLING THROUGH A TRAVIS COUNTY CLERK BUILDING IN CASE STATE REPUBLICAN LEADERS GOT WIND AND INTERVENED.

WITHIN HOURS, THE TEXAS SUPREME COURT HAD BLOCKED OTHER GAY COUPLES FROM GETTING MARRIED UNDER SIMILAR SPECIAL EXCEPTIONS — BUT DIDN'T ADDRESS THE WOMEN'S MARRIAGE, WHICH PAXTON SAID HE CONSIDERED VOID.

BUT THAT REMAINS IN DISPUTE, AND PAXTON SPOKEWSWOMAN CYNTHIA MEYER SAID THEIR OFFICE WILL FILE ADDITIONAL PAPERWORK WITH THE STATE SUPREME COURT ON FRIDAY TO ARGUE THEIR CASE.

\"ACTIVIST JUDGES DON'T CHANGE TEXAS LAW AND WE WILL CONTINUE TO AGGRESSIVELY DEFEND THE LAWS OF OUR STATE,\" PAXTON SAID IN A STATEMENT.

NEW REPUBLICAN TEXAS GOV. GREG ABBOTT ALSO REAFFIRMED HIS SUPPORT FOR TEXAS' CONSTITUTIONAL BAN ON SAME-SEX MARRIAGE THAT VOTERS OVERWHELMINGLY APPROVED IN 2005.

THE WOMEN WERE GRANTED A ONE-TIME LICENSE AFTER AN AUSTIN PROBATE JUDGE THIS WEEK RULED THE STATE'S GAY MARRIAGE BAN UNCONSTITUTIONAL IN AN ESTATE CASE THAT WAS UNRELATED TO THE COUPLE. SENSING AN OPPORTUNITY, GOODFRIEND AND BRYANT POUNCED AND HAD THEIR LAWYER PETITION THE JUDGE THURSDAY MORNING.

STATE DISTRICT JUDGE DAVID WAHLBERG, AN ELECTED DEMOCRAT, SIDED WITH THE COUPLE AND DIRECTED TRAVIS COUNTY OFFICIALS TO STOP RELYING ON \"THE UNCONSTITUTIONAL TEXAS PROHIBITIONS AGAINST SAME-SEX MARRIAGE AS A BASIS FOR NOT ISSUING A MARRIAGE LICENSE.\"

BRYANT SAID THAT BEING LEGALLY MARRIED TO GOODFRIEND WOULD ENSURE INHERITANCE AND ALLOW THE COUPLE TO MAKE MEDICAL DECISIONS FOR EACH OTHER SHOULD ONE OF THEM BECOME CRITICALLY ILL.

COURTS IN INDIANA MADE A SIMILAR EXCEPTION FOR A LESBIAN COUPLE IN APRIL BECAUSE ONE OF THE WOMEN WAS DYING OF CANCER AND WANTED HER PARTNER'S NAME ON HER DEATH CERTIFICATE. A FEDERAL APPEALS COURT OVERTURNED INDIANA'S BAN IN SEPTEMBER.

A FEDERAL JUDGE IN SAN ANTONIO LAST YEAR OVERTURNED TEXAS' SAME-SEX MARRIAGE BAN BUT PUT HIS RULING ON HOLD WHILE THE STATE APPEALS TO THE 5TH U.S. CIRCUIT COURT OF APPEALS.

\"WE ARE ALL WAITING FOR A FINAL DECISION ON MARRIAGE EQUALITY,\" SAID TRAVIS COUNTY CLERK DANA DEBEAUVOIR, WHOSE OFFICE ISSUED THE MARRIAGE LICENSE. \"HOWEVER, THIS COUPLE MAY NOT GET THE CHANCE TO HEAR THE OUTCOME OF THIS ISSUE BECAUSE ONE PERSON'S HEALTH.\"

GOODFRIEND, POLICY DIRECTOR FOR STATE REP. CELIA ISRAEL, SAID DURING A NEWS CONFERENCE THAT HER LAST CHEMOTHERAPY TREATMENT WAS 4 ½ MONTHS AGO. BUT, SHE ADDED: \"ALL OF US WONDER IF THE CANCER GROWS BACK ALONG WITH THE HAIR GROWING BACK.\"

BRYANT, AN AUSTIN LAWYER WHO WORKS ON ADOPTIONS FOR SAME-SEX COUPLES, SAID SHE AND HER WIFE BELIEVE THEIR MARRIAGE LICENSE REMAINS VALID.

MARK PHARISS, WHO ALONG WITH HIS PARTNER ARE LEADING THE TEXAS GAY MARRIAGE LAWSUIT IN FEDERAL COURT, SAID HE WAS \"THRILLED\" BY NEWS OF THE NUPTIALS EVEN THOUGH IT'S UNLIKELY TO IMPACT THEIR BIGGER CASE. HE SAID BRYANT AND GOODFRIEND'S CIRCUMSTANCE \"IS EVIDENCE OF THE HARM THE BAN IS HAVING ON THE STATE.\"

SHORTLY AFTER NEWS OF THE MARRIAGE SPREAD ONLINE, TRAVIS COUNTY OFFICIALS SAID TWO OTHER SAME-SEX COUPLES INQUIRED ABOUT MARRIAGE LICENSES. BY THEN, PAXTON'S OFFICE WAS ALREADY PREPARING ITS EMERGENCY FILING WITH THE STATE SUPREME COURT.

\"THE AG CAN DO WHAT HE WANTS. THIS IS A VERY GOOD DAY IN TEXAS FOR PROGRESSIVELY-MINDED PEOPLE, MUCH LESS LESBIAN AND GAY PEOPLE,\" SAID STEVEN TOMLINSON, WHO CELEBRATED WITH GOODFRIEND AND BRYANT AT THEIR PARTY TUESDAY NIGHT.

READ MORE HERE: HTTP://WWW.MIAMIHERALD.COM/NEWS/NATION-WORLD/ARTICLE10731788.HTML#STORYLINK=CPY

LOS ANGELES –  A \"SUPERBUG\" OUTBREAK SUSPECTED IN THE DEATHS OF TWO LOS ANGELES HOSPITAL PATIENTS IS RAISING DISTURBING QUESTIONS ABOUT THE DESIGN OF A HARD-TO-CLEAN MEDICAL INSTRUMENT USED ON MORE THAN HALF A MILLION PEOPLE IN THE U.S. EVERY YEAR.

AT LEAST SEVEN PEOPLE -- TWO OF WHOM DIED -- HAVE BEEN INFECTED WITH A POTENTIALLY LETHAL, ANTIBIOTIC-RESISTANT STRAIN OF BACTERIA AFTER UNDERGOING ENDOSCOPIC PROCEDURES AT RONALD REAGAN UCLA MEDICAL CENTER BETWEEN OCTOBER AND JANUARY. MORE THAN 170 OTHER PATIENTS MAY ALSO HAVE BEEN EXPOSED, HOSPITAL OFFICIALS SAID.

THE INFECTIONS MAY HAVE BEEN TRANSMITTED THROUGH TWO CONTAMINATED ENDOSCOPES THAT WERE USED TO DIAGNOSE AND TREAT PANCREATIC AND BILE-DUCT PROBLEMS. THE INSTRUMENTS WERE FOUND TO HAVE \"EMBEDDED\" INFECTIONS EVEN THOUGH THEY HAD BEEN CLEANED ACCORDING TO MANUFACTURER'S INSTRUCTIONS, SAID DR. ROBERT CHERRY, THE HOSPITAL'S CHIEF MEDICAL AND QUALITY OFFICER. FIVE OTHER SCOPES WERE CLEARED.

HOSPITAL OFFICIALS SAID THEY IMMEDIATELY REMOVED CONTAMINATED MEDICAL DEVICES AND ADOPTED MORE STRINGENT STERILIZATION TECHNIQUES.

AT A NEWS CONFERENCE THURSDAY AFTERNOON, HEALTH OFFICIALS SOUGHT TO REASSURE THE PUBLIC THAT THERE IS NO BROAD DANGER.

\"THIS OUTBREAK IS NOT A THREAT TO PUBLIC HEALTH,\" SAID DR. BENJAMIN SCHWARTZ, DEPUTY DIRECTOR OF ACUTE COMMUNICABLE DISEASE CONTROL AND PREVENTION FOR THE LA COUNTY DEPARTMENT OF PUBLIC HEALTH.

INFECTIONS OF CARBAPENEM-RESISTANT ENTEROBACTERIACEAE, OR CRE, HAVE BEEN REPORTED AT HOSPITALS AROUND THE COUNTRY, AND SOME HAVE BEEN LINKED TO THE TYPE OF ENDOSCOPE USED AT UCLA. THE DUODENOSCOPE IS A THIN, FLEXIBLE FIBER-OPTIC TUBE THAT IS INSERTED DOWN THE THROAT TO ENABLE A DOCTOR TO EXAMINE AN ORGAN. IT TYPICALLY HAS A LIGHT AND A MINIATURE CAMERA.

DOCTORS FIRST DISCOVERED THE PROBLEM IN MID-DECEMBER WHEN A PATIENT UNDERWENT AN ENDOSCOPIC PROCEDURE AND DEVELOPED AN INFECTION THAT COULDN'T BE TREATED WITH ANTIBIOTICS.

AN INVESTIGATION WAS LAUNCHED AND DOCTORS EMPLOYED HIGH-TECH TECHNIQUES TO FIND OTHER CASES -- A PROCESS THAT TOOK SEVERAL WEEKS, SAID DR. ZACHARY RUBIN, MEDICAL DIRECTOR OF CLINICAL EPIDEMIOLOGY AND INFECTION PREVENTION.

IT WAS DETERMINED THAT CRE INFECTIONS HAD BEEN PASSED ON FROM ONE \"SOURCE CASE\" PATIENT BETWEEN OCT. 3 AND JAN. 28, RUBIN SAID.

THE HOSPITAL HAS NOTIFIED POTENTIALLY EXPOSED PATIENTS THROUGH LETTERS AND PHONE CALLS AND IS OFFERING FREE TESTING AND TREATMENT OPTIONS.

ATTORNEY KEVIN BOYLE SAID THURSDAY THAT ONE OF HIS CLIENTS, AN 18-YEAR-OLD STUDENT, WAS AMONG THOSE INFECTED AFTER HE ENTERED THE HOSPITAL FOR A PROCEDURE THAT INVOLVED USING AN ENDOSCOPE TO EXAMINE HIS PANCREAS.

\"AFTER HE HAD THE PROCEDURE HE WAS RELEASED. THEN HE CAME DOWN WITH HIS ILLNESS, AND WHEN THEY STUDIED HIM AND NOTICED HE HAD THE CRE BACTERIA IN HIM THEY QUICKLY PUT TWO AND TWO TOGETHER,\" HE SAID.

BOYLE DECLINED TO RELEASE THE TEENAGER'S NAME OR SAY WHERE HE ATTENDS SCHOOL BUT SAID HE SPENT 83 DAYS IN THE HOSPITAL AT ONE POINT AND WAS RELEASED BUT RECENTLY RELAPSED AND IS CURRENTLY HOSPITALIZED. HE SAID THE FAMILY DOESN'T BLAME UCLA BUT IS CONSIDERING SUING THE ENDOSCOPE'S MANUFACTURER.

HEALTH INSPECTORS VISITED UCLA AFTER BEING NOTIFIED AND FOUND \"NO BREAKS AND NO BREACHES\" IN ITS DISINFECTION PROCESS, SCHWARTZ SAID.

\"YOU CAN VERY EASILY DO EVERYTHING RIGHT AND STILL HAVE SOME CONTAMINATION,\" SAID DR. DEVERICK ANDERSON, AN INFECTIOUS-DISEASE EXPERT AT DUKE UNIVERSITY. \"WE'RE FINDING THIS IS A PROBLEM, BUT IT'S PROBABLY ONE THAT WE DON'T HAVE A VERY GOOD SOLUTION TO RIGHT NOW.\"

THE U.S. FOOD AND DRUG ADMINISTRATION ON THURSDAY ISSUED AN ADVISORY WARNING DOCTORS THAT EVEN WHEN A MANUFACTURER'S CLEANING INSTRUCTIONS ARE FOLLOWED, GERMS MAY LINGER. THE DEVICE'S COMPLEX DESIGN AND TINY PARTS MAKE COMPLETE DISINFECTION EXTREMELY DIFFICULT, THE ADVISORY SAID. BETWEEN JANUARY 2013 AND DECEMBER 2014, THE FDA RECEIVED 75 REPORTS INVOLVING 135 PATIENTS IN THE U.S. WHO MAY HAVE BEEN INFECTED BY TAINTED SCOPES.

IN A STATEMENT, THE FDA SAID IT IS TRYING TO DETERMINE WHAT MORE CAN BE DONE TO REDUCE SUCH INFECTIONS. BUT IT SAID THAT PULLING THE DEVICE FROM THE MARKET WOULD DEPRIVE HUNDREDS OF THOUSANDS OF PATIENTS OF \"THIS BENEFICIAL AND OFTEN LIFE-SAVING PROCEDURE.\"

\"THE FDA BELIEVES AT THIS TIME THAT THE CONTINUED AVAILABILITY OF THESE DEVICES IS IN THE BEST INTEREST OF THE PUBLIC HEALTH,\" THE AGENCY SAID.

THE MANUFACTURER OF THE DEVICES, OLYMPUS CORP. OF THE AMERICAS, AN ARM OF JAPAN'S OLYMPUS CORP., SAID IN A STATEMENT THAT IT EMPHASIZES THE IMPORTANCE OF METICULOUS MANUAL STERILIZATION OF ITS INSTRUMENTS. IT SAYS IT IS GIVING NEW SUPPLEMENTAL INSTRUCTIONS TO USERS OF THE ENDOSCOPES AND IS WORKING WITH THE FDA ON THE INFECTION PROBLEM.

THE COMPANY IS ALSO BEING INVESTIGATED FOR POSSIBLE VIOLATIONS OF FALSE CLAIMS AND ANTI-KICKBACK LAWS. IT DISCLOSED FEB. 6 THAT IT HAS BEEN UNDER FEDERAL INVESTIGATION SINCE 2011 FOR POSSIBLE VIOLATIONS OF LAWS THAT TYPICALLY BAN IMPROPER PAYMENTS TO DOCTORS OR OTHER CUSTOMERS.

THAT STATEMENT SAID THE COMPANY IS TALKING WITH THE JUSTICE DEPARTMENT TO \"RESOLVE THE MATTERS UNDER INVESTIGATION.\"

A LINGUISTICS EXPERT BELIEVES THE MAN WHO THREATENS THE WEST IN AN ISLAMIC STATE VIDEO PURPORTEDLY SHOWING THE BEHEADING OF 21 COPTIC CHRISTIANS WAS EDUCATED IN THE UNITED STATES.

BUT ERICK THOMAS, A PROFESSOR OF ACOUSTICS AND DIALECTS AT NORTH CAROLINA STATE UNIVERSITY, SAYS IT'S UNCLEAR WHETHER THE MYSTERIOUS, SHROUDED FIGURE IN THE VIDEO RELEASED ON SUNDAY IS FROM THE U.S.

\"HE CLEARLY SPENT A SIGNIFICANT AMOUNT OF HIS CHILDHOOD IN THE UNITED STATES,\" THOMAS TOLD GRETCHEN CARLSON ON \"THE REAL STORY\" WEDNESDAY AFTERNOON. \"WHETHER IT WAS ALL OF HIS CHILDHOOD OR NOT, I COULDN'T SAY THAT. I WOULD SAY PROBABLY FROM THE TIME HE BEGAN HIS SCHOOLING, HE WAS IN THE UNITED STATES, BUT HE WAS PROPERLY EXPOSED TO ARABIC ALL ALONG.\"

THOMAS CITED THE MAN'S USE OF A \"HARD G\" IN TWO INSTANCES: WHEN HE SAYS \"CHOPPING OFF\" AND \"FIGHTING US.\" HE ALSO SAID HIS PRONUNCIATION OF THE LETTER \"O\" IN \"ROME\" MIGHT BE A CLUE OF HIS UPBRINGING AS WELL.

\"IT'S A GOOD SIGN OF INFLUENCE FROM ANOTHER LANGUAGE,\" THOMAS SAID.

AS SEVERAL MEN IN ORANGE JUMPSUITS ARE LED TO A BEACH WHERE THEY ARE BELIEVED TO HAVE BEEN BEHEADED, ONE MILITANT, DRESSED DIFFERENTLY THAN THE OTHERS, ADDRESSES THE CAMERA.

\"HE CLEARLY SPENT A SIGNIFICANT AMOUNT OF HIS CHILDHOOD IN THE UNITED STATES.\"
- ERICK THOMAS, PROFESSOR OF ACOUSTICS AND DIALECTS AT NORTH CAROLINA STATE UNIVERSITY
\"ALL CRUSADERS: SAFETY FOR YOU WILL BE ONLY WISHES, ESPECIALLY IF YOU ARE FIGHTING US ALL TOGETHER,\" THE MILITANT SAYS. \"THEREFORE WE WILL FIGHT YOU ALL TOGETHER,\" HE SAID. \"THE SEA YOU HAVE HIDDEN SHEIKH USAMA BIN LADEN'S BODY IN, WE SWEAR TO ALLAH WE WILL MIX IT WITH YOUR BLOOD.\"

ALSO ON WEDNESDAY, A TOP IRAQI DIPLOMAT TOLD WORLD LEADERS THAT ISIS IS HARVESTING THE ORGANS OF ITS VICTIMS TO FUND IT MURDEROUS OPERATIONS, THE LATEST CHARGE OF BARBARITY IN A LIST THAT ALREADY INCLUDES MASS BEHEADINGS, BURNING PEOPLE ALIVE, CRUCIFYING CHILDREN AND THROWING PEOPLE OFF OF BUILDINGS.

THE SHOCKING NEW CLAIM WAS PRESENTED BY THE IRAQI AMBASSADOR TO THE UNITED NATIONS, WHO SAID BODIES HAVE TURNED UP IN MASS GRAVES BEARING SURGICAL INCISIONS AND MISSING ORGANS SUCH AS KIDNEYS. AMBASSADOR MOHAMED ALHAKIM LEVELED THE CHARGE AS HE ASKED THE SECURITY COUNCIL TO INVESTIGATE WHETHER HARVESTING AND SELLING THE ORGANS OF THOSE IT EXECUTES. THE CLAIM FOLLOWED AN UNCONFIRMED REPORT LATE TUESDAY THAT AS MANY AS 45 PEOPLE CAPTURED BY THE ISLAMIC STATE IN THE ANBAR PROVINCE TOWN OF AL-BAGHDADI HAD BEEN ROUNDED UP AND BURNED ALIVE.

\"WE HAVE BODIES,\" ALHAKIM TOLD HIS INTERNATIONAL COUNTERPARTS. \"COME AND EXAMINE THEM. IT IS CLEAR THEY ARE MISSING CERTAIN PARTS.\"

ALHAKIM, WHO SAID A DOZEN DOCTORS HAVE BEEN EXECUTED IN MOSUL FOR REFUSING TO PARTICIPATE IN ORGAN HARVESTING, BRIEFED THE COUNCIL ON THE OVERALL SITUATION IN IRAQ AND ACCUSED THE ISLAMIC STATE GROUP OF \"CRIMES OF GENOCIDE\" IN TARGETING CERTAIN ETHNIC GROUPS. THE OUTGOING U.N. ENVOY TO IRAQ, NIKOLAY MLADENOV, TOLD THE COUNCIL THAT 790 PEOPLE WERE KILLED IN JANUARY ALONE BY TERRORISM AND ARMED CONFLICT.

MLADENOV NOTED THE INCREASING NUMBER OF REPORTS AND ALLEGATIONS THAT THE ISLAMIC STATE GROUP IS USING ORGAN HARVESTING AS A FINANCING METHOD, BUT HE SAID ONLY THAT \"IT'S VERY CLEAR THAT THE TACTICS ISIL IS USING EXPAND BY THE DAY.\" HE USED AN ACRONYM FOR THE GROUP.

HE SAID IRAQ'S MOST PRESSING GOAL IS TO WIN BACK THE VAST TERRITORY THAT THE ISLAMIC STATE HAS SEIZED IN THE PAST YEAR. THE SUNNI MILITANTS SEIZED A THIRD OF BOTH IRAQ AND NEIGHBORING SYRIA AND IMPOSED STRICT SHARIA LAW.

\"ESPECIALLY WORRYING IS THE INCREASING NUMBER OF REPORTS OF REVENGE ATTACKS COMMITTED PARTICULARLY AGAINST MEMBERS OF THE SUNNI COMMUNITY IN AREAS LIBERATED FROM ISIL CONTROL,\" MLADENOV SAID.

THE IDENTITIES OF THE VICTIMS WHO WERE REPORTEDLY BURNED ALIVE TUESDAY IN AL-BAGHDADI ARE NOT CLEAR, THE LOCAL POLICE CHIEF TOLD THE BBC. ISIS FIGHTERS REPORTEDLY CAPTURED MOST OF THE TOWN LAST WEEK.

NAVY REAR ADM. JOHN KIRBY, A PENTAGON SPOKESMAN, SAID WEDNESDAY THAT U.S. AUTHORITIES WERE AWARE OF A VIDEO PURPORTEDLY SHOWING THE EXECUTIONS, BUT THAT OFFICIALS HAD NOT YET VERIFIED ITS AUTHENTICITY, FOX NEWS' MARTHA MCCALLUM SAID ON \"THE O'REILLY FACTOR.\"

AL-BAGHDADI, WHICH IS ABOUT 50 MILES NORTHWEST OF RAMADI IN ANBAR PROVINCE, IS LOCATED ABOUT FIVE MILES FROM AIN AL-ASAD AIR BASE, WHERE 400 U.S. MILITARY PERSONNEL ARE TRAINING IRAQI SOLDIERS AND SUNNI TRIBESMEN TO TAKE ON ISIS. THE BASE WAS RAIDED LAST WEEK BY A SMALL BAND OF FIGHTERS, IN WHAT SOME EXPERTS BELIEVE MAY HAVE BEEN A PROBE IN PREPARATION FOR A FULL-SCALE ATTACK.

THE BASE HAS BEEN THE TARGET OF SPORADIC MORTAR FIRE IN PAST WEEKS, AND THE JIHADIST ARMY HAS BEEN MOVING FORCES FROM ITS STRONGHOLDS IN SYRIA TO ANBAR PROVINCE, POSSIBLY SETTING THE STAGE FOR A MAJOR CLASH WITH FORCES ON THE BASE THAT IS NOW THE SOLE BULWARK BETWEEN ISIS AND BAGHDAD.

THERE ARE CURRENTLY NEARLY 2,600 U.S. FORCES IN IRAQ, INCLUDING ABOUT 450 WHO ARE TRAINING IRAQI TROOPS AT THREE BASES ACROSS THE COUNTRY, INCLUDING AL-ASAD. FORCES FROM OTHER COALITION COUNTRIES CONDUCT THE TRAINING AT THE FOURTH SITE, IN THE NORTHERN CITY OF IRBIL.

BUT EVEN IF ISIS MILITANTS CLOSE IN ON THE BASE, TAKING IT WOULD REQUIRE A MASSIVE FORCE, THAT WOULD PRESENT A TARGET FOR AIRSTRIKES, RETIRED COL. THOMAS LYNCH, A NATIONAL DEFENSE UNIVERSITY FELLOW, TOLD FOX NEWS.

THE ASSOCIATED PRESS CONTRIBUTED TO THIS REPORT.

ADVERTISEMENT
MORE ON THIS...


REPORT: DOZENS OF IRAQI CITIZENS BURNED ALIVE BY ISIS

PESHMERGA FORCES BATTLE ISIS NEAR KURDISH CAPITAL OF IRBIL

ISIS ATROCITY OVERSHADOWS WHITE HOUSE SUMMIT ON EXTREMISM
 ISIS REPORTEDLY PLANS TO SEND FIGHTERS TO SOUTHERN EUROPE DISGUISED AS MIGRANTS

IS ISIS GAINING A STRONGHOLD IN LIBYA?
 FRANCE TRACKING 400 BELIEVED TO BE IN TERROR SLEEPER CELLS
WORLD VIDEO
 PACIFISTS AND THE WAR AGAINST ISLAMIC TERRORPLAY VIDEO
PACIFISTS AND THE WAR AGAINST ISLAMIC TERROR
 US CONDEMNS ISIS BEHEADINGS OF 21 EGYPTIAN CHRISTIANSPLAY VIDEO
US CONDEMNS ISIS BEHEADINGS OF 21 EGYPTIAN CHRISTIANS
 ITALY BOOSTS SECURITY AMID GROWING ISIS CONCERNSPLAY VIDEO
ITALY BOOSTS SECURITY AMID GROWING ISIS CONCERNS
 HOW SHOULD MEDIA HANDLE ISIS VIOLENCE?PLAY VIDEO
HOW SHOULD MEDIA HANDLE ISIS VIOLENCE?
TRENDING IN WORLD
1 WEDDING ENDS IN BRAWL AFTER BRIDE MARRIES GUEST INSTEAD OF GROOM
2 FIGURE IN ISIS MASS BEHEADING VIDEO COULD HAVE US TIES, LINGUISTIC EXPERT SAYS
3 COSSACK FIGHTERS CELEBRATE IN DEBALTSEVE AS UKRAINIAN FORCES DESCRIBE HARROWING RETREAT
4 CARACAS MAYOR WHO OPPOSED VENEZUELA GOVERNMENT ARRESTED
5 ISIS MILITANTS REPORTEDLY SEEK MEDICATION TO FUEL 'ABNORMAL' SEXUAL BEHAVIORS
SEE ALL TRENDS
FOX NEWS SALUTES
MORE
TERROR GROUP APPEARS TO MAKES THREAT PERSONAL BY SENDING THREATENING MESSAGES ONLINE TO SEVERAL AMERICAN MILITARY SPOUSES
ISIS THREATENS MILITARY SPOUSES ONLINE
US SENATOR MUM ON REPORTED PAYOUT DEAL WITH STAFFER AMID VA SCANDAL
WORLD WAR II VETERAN FINALLY RECEIVES HIGH SCHOOL DIPLOMA

ADVERTISEMENT

SPONSORED STORIES YOU MAY LIKE

RUMORS AND LEAKS ABOUT APPLE'S ELECTRIC VEHICLE, WHICH MAY OR MAY NOT BE SELF-DRIVING, JUST KEEPS ON POURING IN. APPLE HAS BEEN KNOWN TO EYE CARS BUT, UNTIL RECENTLY, EVERYONE PRESUMED IT WAS JUST FOR IN-VEHICLE INFOTAINMENT SYSTEMS. NOW INSIDER SOURCES ARE REVEALING JUST HOW AGGRESSIVE CUPERTINO'S AUTOMOBILE PUSH REALLY IS, SAYING THAT THE IPHONE MAKER IS EYING A 2020 DEADLINE FOR ITS RUMORED TITAN EV. THAT IS, OF COURSE, IF IT MANAGES TO OVERCOME NOT JUST TECHNOLOGICAL HURDLES BUT RECENT NEW LEGAL PROBLEMS AS WELL.

RUMORS OF APPLE'S DEEPER FORAY INTO THE AUTOMOTIVE INDUSTRY CAME TO A HEAD THIS MONTH WITH SIGHTINGS OF A STRANGE CAR ROAMING THE STREETS THAT WAS LINKED TO THE COMPANY. WHILE THERE IS STILL SOME DEBATE ON WHETHER THE END PRODUCT WAS FOR AN AUTONOMOUS CAR, OR FOR MAPPING, ALMOST ALL SEEM TO AGREE THAT APPLE IS AT LEAST EYING A BATTERY-POWERED VEHICLE.

AS TESLA WOULD ATTEST, THE BATTERY IS ONE OF THE BIGGEST CHALLENGES FOR AN EV, BUT IN APPLE'S CASE, THAT PROBLEM IS MORE THAN JUST TECHNICAL. IN ORDER TO JUMPSTART ITS CAR DEVELOPMENT, BATTERY MAKER A123 SYSTEMS LLC ALLEGES THAT APPLE INITIATED AN AGGRESSIVE TARGETED CAMPAIGN TO POACH ITS EMPLOYEES, WHICH RESULTED IN VIOLATIONS OF NON-DISCLOSURE AGREEMENTS OR NDAS. APPLE NOW FACES A LAWSUIT IN BOSTON'S FEDERAL COURT, WHICH COULD FOIL OR AT LEAST DELAY ITS SCHEDULE.

EXPERTS SAY THAT A CAR MAKER USUALLY SPENDS FIVE TO SEVEN YEARS DEVELOPING A CAR. TEN IF YOU'RE STARTING FROM SCRATCH. IN THAT CONTEXT, APPLE'S 2020 PLAN SEEMS VERY AMBITIOUS AND PROBABLY SPEAKS OF THE COMPANY'S AGGRESSIVE AGENDA. THAT SAID, TESLA PROVED THAT YOU DO NOT NEED TO BE A WELL-ESTABLISHED AUTOMOBILE MAKER TO PULL OF A SUCCESSFUL ELECTRIC VEHICLE, AND APPLE MIGHT VERY WELL BE TAKING INSPIRATION FROM THAT. SOURCES CLAIM THAT THE COMPANY'S TEAM DEDICATED TO THIS TASK ALREADY HAS 200 MEMBERS AND, AS A123 POINTS OUT, IT IS STILL TRYING TO GRAB MORE, PARTICULARLY THOSE FROM THE BATTERY INDUSTRY.

THAT'S NOT TO SAY, HOWEVER, THAT WE WILL SEE AN APPLE TITAN CAR BY 2020. DESPITE THIS SEEMINGLY FOCUSED ATTEMPT, THE ENTIRE PROJECT COULD BE SCRAPPED IN AN INSTANT IF THE COMPANY'S EXECUTIVES ARE NOT SATISFIED BY THE PROGRESS WITHIN THAT TIMEFRAME. IF ALL OF THESE ARE TRUE, THEN THE PRESSURE IS DEFINITELY ON. ESPECIALLY FOR APPLE AND CEO TIM COOK WHO FACE THE CHALLENGE OF COMING OUT WITH NEW PRODUCTS THAT WILL ONCE AGAIN RESHAPE THE MARKET THE WAY THE IPOD DID


"

puts text.split(" ").map { |e| e.split("").reject {|e|!("ABCDEFGHIJKLMNOPQRSTUVWZYZ".chars.include?(e))}.join }.reject{|e|((e.length>8)||(e.length<2))}.uniq.map { |e| "\"#{e}\"" }.join(",")