# text="
# hut cam soy bull nun coy soy gel peg cafe cease hug pear peer adultery app bog bee bulk bean butt bull bracket breed cum deter determined dull doll donkey dolly eradicate earie fort faulty frog froggy faggot fag gasoline gall bladder
# "

text="
NBC BAY AREA
57° NEWSLETTERS | SEND PICS | TIPS GO
HOME
NEWS
WEATHER
INVESTIGATIVE UNIT
ENTERTAINMENT
SPORTS
TRAFFIC
CONTACT US
WATCH LIVE TV NOW
LOCALCALIFORNIAU.S. & WORLDSPORTSHEALTHTECHWEIRDWEATHERREAL ESTATEBLOGS:PRESS HERETHE COVE
LIVE
VIDEO
WATCH NBC BAY AREA NEWS AT 11
SHARE
FACEBOOKTWITTER


NEWS > LOCAL
RESIDENTS WORRY ABOUT DUST AS CANDLESTICK PARK EXTERIOR TORN DOWN
BY CHRISTIE SMITH
VIEW COMMENTS () | EMAIL | PRINT

TRENDING STORIES
PHOTOSWATCH: SUPPORTERS DETAIL RAIDERS-CHARGERS STADIUM PROPOSAL
VIDEO\"GREAT BLOW\" IF RAIDERS MOVE TO LA: COUNCILMAN
VIDEOCURIOUS CROW VIDEOBOMBS LEVI'S STADIUM CAMERA
VIDEOIS OAKLAND REALLY CA'S MOST CRIME-RIDDEN CITY?
WATCH NBC BAY AREA NEWS AT 11
WEATHER FORECAST
SAN FRANCISCO, CA
 57°
SCATTERED CLOUDS
FEELS LIKE 57°
 RADAR FORECAST MAPS

NEWSLETTERS
RECEIVE THE LATEST LOCAL UPDATES IN YOUR INBOX


PRIVACY POLICY | MORE NEWSLETTERS



THE WALLS CRASHING DOWN AT CANDLESTICK PARK IN SAN FRANCISCO ARE RAISING HEALTH CONCERNS IN THE NEIGHBORHOOD. CHRISTIE SMITH REPORTS. (PUBLISHED THURSDAY, FEB 19, 2015)
UPDATED AT 5:34 PM PST ON THURSDAY, FEB 19, 2015
THE WALLS CRASHING DOWN AT CANDLESTICK PARK IN SAN FRANCISCO ARE RAISING HEALTH CONCERNS IN THE NEIGHBORHOOD.
THE ICONIC FORMER HOME OF THE 49ERS AND GIANTS IS ALMOST ENTIRELY GUTTED. CREWS ON THURSDAY BEGAN TEARING DOWN THE EXTERIOR OF THE STADIUM.
VIDEODEMOLITION OF CANDLESTICK PARK UNDERWAY
A DEVELOPER IS BUILDING A HOTEL, SHOPPING CENTER AND APARTMENTS TO REPLACE CANDLESTICK PARK.
RESIDENT SHIRLEY MOORE CAN SEE THE WORK FROM HER HOUSE AND IS CONCERNED WITH ASBESTOS DUST AND RESPIRATORY ILLNESS IN HER NEIGHBORHOOD.
CANDLESTICK DEMOLITION UNDERWAY[BAY] CANDLESTICK DEMOLITION UNDERWAY
THE ICONIC FORMER HOME OF THE 49ERS AND GIANTS IS ENTIRELY GUTTED. ON FRIDAY, CREWS WILL TEAR DOWN THE STADIUM'S EXTERIOR. (PUBLISHED WEDNESDAY, FEB 18, 2015)
\"MY CONCERN IS THE DUST. IT HAS ALWAYS BEEN THE DUST AND THE VIOLATION OF THE DUST ENVIRONMENTALLY,\" MOORE SAID. \"WE ARE JUST SITTING DUCKS AS FAR AS THE DUST FROM THIS STADIUM AND THE PARTICULATES THAT COME THROUGH OUR WINDOW.\"
MOORE ALSO SAID SHE IS CONCERNED ABOUT TRANSPARENCY FROM THE DEVELOPER.
\"THEY CLAIM TO HAVE PUT DUST MONITORS OUT HERE TO MONITOR THE DUST AND THE PARTICULATES,\" SHE SAID. \"THERE WERE SUPPOSED TO BE SIX MONITORS -- THEY ONLY HAVE TWO.\"
DEVELOPER LENNAR URBAN SAID THERE ARE EIGHT MONITORS ON CANDLESTICK POINT, WITH FOUR BEING USED FOR PARK DEMOLITION. LENNAR URBAN ALSO SAID THEY FOLLOW A DUST MITIGATION PLAN APPROVED BY THE DEPARTMENT OF PUBLIC HEALTH.
AN ENVIRONMENTAL HEALTH INSPECTOR SAID THE LAST REPORT FOUND NO VISIBLE DUST, AND TRUCKS WERE BEING CLEANED BEFORE LEAVING THE SITE.



61°F SAN FRANCISCO

SIGN INREGISTER
NEWS
SPORTS
BUSINESS
A&E
FOOD
LIVING
TRAVEL
REAL ESTATE
CARS
JOBS
SFCHRONICLE
FIND&SAVE
KING TIDES AT CANDLESTICK POINT OFFER GLIMPSE OF PLANET’S FUTURE
BY KURTIS ALEXANDER UPDATED 4:04 PM, WEDNESDAY, FEBRUARY 18, 2015

4





 ISAAC DE LA CRUZ, 17 YEAR OLD STUDENT FROM DOWNTOWN HIGH SCHOOL, USES A PICK AXE TO PREPARE SOIL FOR PLANTINGS AT YOSEMITE SLOUGH AT CANDLESTICK POINT STATE PARK IN SAN FRANCISCO, CALIFORNIA ON WEDNESDAY, FEBRUARY 18, 2015.  HE IS PART OF THE WILDERNESS ARTS AND LITERACY COLLABORATIVE AS THEY WORK TO RESTORE THE SLOUGH. PHOTO: LIZ HAFALIA / THE CHRONICLE / ONLINE_YES
PHOTO: LIZ HAFALIA / THE CHRONICLE
IMAGE 1 OF 5
ISAAC DE LA CRUZ, 17 YEAR OLD STUDENT FROM DOWNTOWN HIGH SCHOOL, USES A PICK AXE TO PREPARE SOIL FOR PLANTINGS AT YOSEMITE SLOUGH AT CANDLESTICK POINT STATE PARK IN SAN FRANCISCO, CALIFORNIA ON WEDNESDAY, FEBRUARY 18, 2015. HE IS PART OF THE WILDERNESS ARTS AND LITERACY COLLABORATIVE AS THEY WORK TO RESTORE THE SLOUGH.
IMAGE 1 OF 5ISAAC DE LA CRUZ, 17 YEAR OLD STUDENT FROM DOWNTOWN HIGH SCHOOL, USES A PICK AXE TO PREPARE SOIL FOR PLANTINGS AT YOSEMITE SLOUGH AT CANDLESTICK POINT STATE PARK IN SAN FRANCISCO, CALIFORNIA ON WEDNESDAY, FEBRUARY 18, 2015. HE IS PART OF THE WILDERNESS ARTS AND LITERACY COLLABORATIVE AS THEY WORK TO RESTORE THE SLOUGH.

AS THIS WEEK’S KING TIDES WASHED OVER A SMALL BEACH AT CANDLESTICK POINT, THE SAN FRANCISCO BAY BECAME AN UNLIKELY CLASSROOM FOR TEACHING THE GRIM REALITY OF SEA-LEVEL RISE.
A HANDFUL OF COMMUNITY ORGANIZERS POINTED TO THE UNUSUALLY HIGH BAY WATER AS A GLIMPSE OF WHAT THE FUTURE WILL LOOK LIKE WITH RISING SEAS — ALL IN A NEIGHBORHOOD WHERE CLIMATE CHANGE MAY NOT BE THE BIGGEST THING ON PEOPLE’S MINDS BUT WHERE IT’S PARTICULARLY RELEVANT.
THE BAYVIEW ON SAN FRANCISCO’S SOUTHEASTERN EDGE, MUCH OF IT BUILT ON LOW-LYING FILL, STANDS TO LOSE AS MUCH COASTLINE AS ANYWHERE IN THE CITY IN COMING DECADES. BY THE END OF THE CENTURY, CLIMATE EXPERTS EXPECT OCEANS TO RISE IN THE REGION AS MUCH AS 3 FEET.
“I COME OUT HERE ALL THE TIME, AND I DIDN’T EVEN REALIZE THE TIDE WAS SO HIGH,” SAID BAYVIEW RESIDENT DEBORAH POWELL, AFTER PAUSING IN HER MORNING WALK TO SPEAK WITH THE ACTIVISTS IN CANDLESTICK POINT STATE RECREATION AREA. “THE WHOLE BEACH IS COVERED WITH WATER.”


WHILE THE HIGH TIDES THIS WEEK ARE NOT THE PRODUCT OF CLIMATE CHANGE — JUST THE UNUSUALLY STRONG GRAVITATIONAL PULL OF THE SUN AND MOON — CLIMATE EXPERTS, AMONG OTHERS, WATCH SUCH EXTREME TIDES TO GET A BETTER IDEA OF WHERE WATER LEVELS MAY BE IN YEARS TO COME.
A SIGN POSTED BY THE COMMUNITY ORGANIZERS NOTING WHERE THE AVERAGE TIDE COULD BE IN 2080 WAS EVEN MORE WORRISOME THAN THIS WEEK’S HIGH WATER. THE MARKER STOOD SEVERAL DOZEN FEET FROM THE BAY — PAST A PAIR OF PICNIC TABLES, ABOVE A COASTAL WALKING TRAIL, AND BEYOND WHERE THE GROUP GATHERED FOR COFFEE AND DOUGHNUTS.
“I DON’T KNOW WHAT I WOULD DO IF THIS AREA WASN’T HERE,” POWELL SAID OF THE PARK. “THIS IS ALMOST MY SANCTUARY OUT HERE.”
SEA LEVELS HAVE BEEN RISING STEADILY SINCE 1900, STUDIES SHOW. HIGHER TEMPERATURES HAVE CAUSED POLAR ICE AND GLACIERS TO MELT, ADDING VOLUME TO THE OCEANS, WHILE AT THE SAME TIME, THE WARMING OCEAN HAS EXPANDED AS IT’S HEATED UP, PER THE LAWS OF NATURE.
SO FAR, WATER HAS RISEN LESS THAN A FOOT ABOVE ITS HISTORICAL NORM, ACCORDING TO THE STUDIES. HOWEVER, THE RATE OF INCREASE IS EXPECTED TO SPEED UP AND BECOME INCREASINGLY PROBLEMATIC FOR COASTAL AREAS.
BETWEEN TUESDAY AND THURSDAY, COASTAL RESIDENTS ARE WITNESSING A TIDE MORE THAN 9 FEET ABOVE ITS AVERAGE LOW AT SOME SPOTS ON THE BAY. THIS ONLY HAPPENS A FEW TIMES A YEAR. THE FINAL EXTREME TIDE THIS WEEK, OFTEN DUBBED A KING TIDE, WILL OCCUR THURSDAY IN THE LATE MORNING AND EARLY AFTERNOON.
THE NATIONAL WEATHER SERVICE HAS ISSUED A FLOOD ADVISORY THROUGH THURSDAY.
ANTHONY KHALIL, A COMMUNITY ORGANIZER AND PROGRAMS MANAGER FOR LITERARY FOR ENVIRONMENTAL JUSTICE, SAID HE AND HIS COLLEAGUES HOPE THE TIDES WILL EDUCATE AND EMPOWER A NEIGHBORHOOD THAT HAS EXPERIENCED MORE THAN ITS FAIR SHARE OF PROBLEMS — BE IT INDUSTRIAL POLLUTION OR POVERTY.
“HISTORY SHOWS THAT THIS IS CONTINUOUSLY ONE OF THE MOST UNDER-SERVED AREAS AND WHERE THE CITY RESPONSE IS SLOWEST,” HE SAID.
WITH FLOODING ALREADY COMMON ON AREA STREETS WHEN RAIN IS HEAVY AND TIDES ARE BIG, KHALIL SAID IT’S TIME FOR RESIDENTS TO START PREPARING FOR A FUTURE WITH CLIMATE CHANGE.
HIS GROUP HAS BEEN HELPING TO RESTORE WETLANDS AROUND CANDLESTICK POINT THAT SERVE AS A BUFFER AGAINST RISING SEAS, AND HE EXPECTS THAT HE AND OTHERS WILL INCREASE COORDINATION WITH THE CITY AND REGIONAL ORGANIZATIONS THAT HAVE BEEN WORKING ON HOW TO DEAL WITH HIGHER OCEAN LEVELS.
ON TUESDAY MORNING, ONLY A HANDFUL OF PEOPLE TOOK NOTE OF KHALIL AND HIS GROUP. THE WEATHER WAS COOL ALONG THE BAY, AND THE ORGANIZERS EXPLAINED THAT MOST RESIDENTS WERE PROBABLY DEALING WITH MORE IMMEDIATE CONCERNS, LIKE GOING TO WORK AND GETTING THEIR KIDS TO SCHOOL.
“SEA-LEVEL CHANGE IS ANOTHER LAYER ON TOP OF WHAT THIS COMMUNITY IS ALREADY FACING,” SAID HEIDI NUTTERS, WHO HELPS RUN SAN FRANCISCO STATE’S SAN FRANCISCO BAY NATIONAL ESTUARINE RESEARCH RESERVE.
NUTTERS, HOWEVER, NOTED THAT THE GROUP IS JUST KICKING OFF ITS AWARENESS CAMPAIGN, AND SHE EXPECTS MORE PEOPLE TO JOIN THE EFFORT TO ADDRESS CLIMATE CHANGE.
KURTIS ALEXANDER IS A SAN FRANCISCO CHRONICLE STAFF WRITER. E-MAIL: KALEXANDER@SFCHRONICLE.COM TWITTER: @KURTISALEXANDER





VIDEOS

HEILEMANN: U.S. SHOULD BOYCOTT 2022 WORLD CUP IN QATAR
BLOOMBERG
KANYE WEST'S TWITTER RANT ABOUT 'BIGOTED' FASHION INDUSTRY
ITN
800K HEALTHCARE.GOV CUSTOMERS GET WRONG TAX INFO
AP
SCHOOLGIRLS RUN AWAY TO JOIN ISIS
SKY NEWS
'MOVIE PROP' HELICOPTER HITS BRIDGE ON 15 FREEWAY IN FONTANA, LANES CLOSED
KTLA - LOS ANGELES
APB FOR QUEEN ELSA - WANTED OVER WINTER STORM
WYMT - LEXINGTON, KY
HEILEMANN: U.S. SHOULD BOYCOTT 2022 WORLD CUP IN QATAR
BLOOMBERG
KANYE WEST'S TWITTER RANT ABOUT 'BIGOTED' FASHION INDUSTRY
ITN
MORE VIDEOS:

'MOVIE PROP' HELICOPTER HITS BRIDGE ON 15 FREEWAY IN FONTANA, LANES CLOSED

APB FOR QUEEN ELSA - WANTED OVER WINTER STORM

HEILEMANN: U.S. SHOULD BOYCOTT 2022 WORLD CUP IN QATAR

KANYE WEST'S TWITTER RANT ABOUT 'BIGOTED' FASHION INDUSTRY

800K HEALTHCARE.GOV CUSTOMERS GET WRONG TAX INFO

SCHOOLGIRLS RUN AWAY TO JOIN ISIS

'MOVIE PROP' HELICOPTER HITS BRIDGE ON 15 FREEWAY IN FONTANA, LANES CLOSED

APB FOR QUEEN ELSA - WANTED OVER WINTER STORM

HEILEMANN: U.S. SHOULD BOYCOTT 2022 WORLD CUP IN QATAR

KANYE WEST'S TWITTER RANT ABOUT 'BIGOTED' FASHION INDUSTRY

800K HEALTHCARE.GOV CUSTOMERS GET WRONG TAX INFO

SCHOOLGIRLS RUN AWAY TO JOIN ISIS
 RETURNING FROM A STRIKE OVER TOKYO, THIS B-29 CAME INTO IWO JIMA FOR AN EMERGENCY LANDING, PLOWED THROUGH FOUR MUSTANG FIGHTERS AND BURST INTO FLAMES ON MAY 10, 1945. TWO MEMBERS OF THE CREW WERE HOSPITALIZED FOR BURNS. MEN IN FOREGROUND CROUCH BESIDE JEEP TO AVOID EXPLODING AMMUNITION. 70 YEARS AGO: THE BATTLE OF IWO JIMA
YOU MIGHT ALSO LIKE
 WHAT’S THE DIFFERENCE BETWEEN DYSGRAPHIA AND DYSLEXIA?WHAT’S THE DIFFERENCE BETWEEN DYSGRAPHIA AND… (UNDERSTOOD)
3 THINGS TO SPEED YOUR WINDOWS SERVER 2003 MIGRATION3 THINGS TO SPEED YOUR WINDOWS SERVER 2003… (MICROSOFT)
MD ANDERSON, MEMORIAL HERMANN DELIVER NEW BREAST SCREENING PROGRAMMD ANDERSON, MEMORIAL HERMANN DELIVER NEW BREAST… (HOUSTON CHRONICLE)
THE ISIS BEHEADINGS YOU WON'T HEAR ABOUTTHE ISIS BEHEADINGS YOU WON'T HEAR ABOUT (VOCATIV)
10 BABY GIRL NAMES THAT USED BE POPULAR10 BABY GIRL NAMES THAT USED BE POPULAR (ANCESTRY)

MOST POPULAR
1 POLICE SAY 19-YEAR-OLD SUSPECT IN VEGAS KILLING WAS GUNMAN
2 OBAMA: PASS A BILL OR I’LL RIP UP THE CONSTITUTION
3 RAIDERS, CHARGERS PONDER SHARED STADIUM NEAR LOS ANGELES
4 20 TOURIST FAUX PAS TO AVOID
5 DA: CAL STUDENT SEXUALLY ASSAULTED FRATERNITY BROTHER
SFGATE LOGO
ON SFCHRONICLE.COM
STAIRS THAT START AT PRAGUE STREET LEAD TO CROCKER AMAZON PLAYGROUND IN S.F.’S EXCELSIOR NEIGHBORHOOD.
DILAPIDATED STAIRWAY IN SAN FRANCISCO’S EXCELSIOR TO GET FIX
WALMART WAGE BUMP NICE, BUT TO EARN MORE, STORES MUST DO MORE
MISSY FRANKLIN TO LEAVE CAL SWIM TEAM TO FOCUS ON OLYMPICS
SUBSCRIBER? IT'S YOURS!ACTIVATE!ACTIVATE FOR ACCESS TO SFCHRONICLE.COM!

YOU MIGHT ALSO LIKE

 KELSEY GRAMMAR'S EX-WIFE, CAMILLE DROPS JAWS IN BIKINI AT THE BEACH
KELSEY GRAMMAR'S EX-WIFE, CAMILLE DROPS JAWS IN BIKINI AT THE… (RADAR ONLINE)
ONE PARTY, HOSTED BY EVERYONE
ONE PARTY, HOSTED BY EVERYONE (MICROSOFT)
AMAZING FOOTAGE CAPTURES SPACEX ROCKET’S CRASH-LANDING
AMAZING FOOTAGE CAPTURES SPACEX ROCKET’S CRASH-LANDING (TECHNOBUFFALO)
MY SON'S FRIENDS THINK I'M HOT?
MY SON'S FRIENDS THINK I'M HOT? (NICK MOM)
FROM AROUND THE WEB

FOR ORGANIZATIONS RUNNING LEGACY WINDOWS SERVER 2003, NOW IS THE TIME TO LOOK TO THE FUTURE (MICROSOFT)
15 CELEBS IN BARELY THERE BIKINIS (STYLEBLAZER)
ASTOUNDING SHOTS FROM THE SHARPEST NEW SATELLITE IN SPACE (PICTURES) (CNET)
LEARN HOW TO COLLECT SUPPORT FOR YOUR TRANSITION AWAY FROM WINDOWS SERVER 2003 (MICROSOFT)
AMAL CLOONEY SHUTS DOWN REPORTER WITH FANTASTIC RESPONSE TO RUDE QUESTION (STIRRING DAILY)
WHAT 36 FEMALE CELEBS REALLY WEIGH (TOPIX)
15 STARS WHO ARE BANKRUPT (SHE BUDGETS)
MORE FROM SFGATE

DROUGHT THREATS FORCE EARLY TROUT RELEASE IN TRUCKEE RIVER
LOW-PROFILE RETAIL TITAN’S GIFT TO UCSF: $100 MILLION
AMERICA'S TOP PUBLIC UNIVERSITIES
S.F. ARCHBISHOP CORDILEONE WIELDS CONTROVERSY TO PROMOTE AGENDA
MASSIVE SFMOMA SCULPTURE SHUTS HOWARD STREET LANES
PHOTOS RELEASED OF ALLEGED MILL VALLEY BANK ROBBER
WALGREENS EMPLOYEES STABBED, BEATEN BY TEENS IN DOWNTOWN SAN FRANCISCO
RECOMMENDED BY


SELECTED VIDEO

4 COMMENTS POWERED BY:
GUEST

RECORD VIDEOUPLOAD VIDEOUPLOAD IMAGESUBMIT
FOLLOW SHOW: 10 | 20 | 50
"
puts text.split(" ").map { |e| e.split("").reject {|e|!("ABCDEFGHIJKLMNOPQRSTUVWZYZ".chars.include?(e))}.join }.reject{|e|((e.length>8)||(e.length<2))}.uniq.map { |e| "\"#{e}\"" }.join(",")