text="
SHE WOKE WITH A GASP, NOT KNOWING WHO SHE WAS, OR WHERE.

THE SMELL OF BLOOD WAS HEAVY IN HER NOSTRILS… OR WAS THAT HER NIGHTMARE, LINGERING? SHE HAD DREAMED OF WOLVES AGAIN, OF RUNNING THROUGH SOME DARK PINE FOREST WITH A GREAT PACK AT HER HELLS, HARD ON THE SCENT OF PREY.

HALF LIGHT FILLED THE ROOM, GREY AND GLOOMY. SHIVERING, SHE SAT UP IN BED AND RAN A HAND ACROSS HER SCALP. STUBBLE BRISTLED AGAINST HER PALM. I NEED TO SHAVE BEFORE IZEMBARO SEES. MERCY, I’M MERCY, AND TONIGHT I’LL BE RAPED AND MURDERED. HER TRUE NAME WAS MERCEDENE, BUT MERCY WAS ALL ANYONE EVER CALLED HER…

EXCEPT IN DREAMS. SHE TOOK A BREATH TO QUIET THE HOWLING IN HER HEART, TRYING TO REMEMBER MORE OF WHAT SHE’D DREAMT, BUT MOST OF IT HAD GONE ALREADY. THERE HAD BEEN BLOOD IN IT, THOUGH, AND A FULL MOON OVERHEAD, AND A TREE THAT WATCHED HER AS SHE RAN.

SHE HAD FASTENED THE SHUTTERS BACK SO THE MORNING SUN MIGHT WAKE HER. BUT THERE WAS NO SUN OUTSIDE THE WINDOW OF MERCY’S LITTLE ROOM, ONLY A WALL OF SHIFTING GREY FOG. THE AIR HAD GROWN CHILLY… AND A GOOD THING, ELSE SHE MIGHT HAVE SLEPT ALL DAY. IT WOULD BE JUST LIKE MERCY TO SLEEP THROUGH HER OWN RAPE.

GOOSEPRICKLES COVERED HER LEGS. HER COVERLET HAD TWISTED AROUND HER LIKE A SNAKE. SHE UNWOUND IT, THREW THE BLANKET TO THE BARE PLANK FLOOR AND PADDED NAKED TO THE WINDOW. BRAAVOS WAS LOST IN FOG. SHE COULD SEE THE GREEN WATER OF THE LITTLE CANAL BELOW, THE COBBLED STONE STREET THAT RAN BENEATH HER BUILDING, TWO ARCHES OF THE MOSSY BRIDGE… BUT THE FAR END OF THE BRIDGE VANISHED IN GREYNESS, AND OF THE BUILDINGS ACROSS THE CANAL ONLY A FEW VAGUE LIGHTS REMAINED. SHE HEARD A SOFT SPLASH AS A SERPENT BOAT EMERGED BENEATH THE BRIDGE’S CENTRAL ARCH. “WHAT HOUR?” MERCY CALLED DOWN TO THE MAN WHO STOOD BY THE SNAKE’S UPLIFTED TAIL, PUSHING HER ONWARD WITH HIS POLE.

THE WATERMAN GAZED UP, SEARCHING FOR THE VOICE. “FOUR, BY THE TITAN’S ROAR.” HIS WORDS ECHOED HOLLOWLY OFF THE SWIRLING GREEN WATERS AND THE WALLS OF UNSEEN BUILDINGS.

SHE WAS NOT LATE, NOT YET, BUT SHE SHOULD NOT DAWDLE. MERCY WAS A HAPPY SOUL AND A HARD WORKER, BUT SELDOM TIMELY. THAT WOULD NOT SERVE TONIGHT. THE ENVOY FROM WESTEROS WAS EXPECTED AT THE GATE THIS EVENING, AND IZEMBARO WOULD BE IN NO MOOD TO HEAR EXCUSES, EVEN IF SHE SERVED THEM UP WITH A SWEET SMILE.

SHE HAD FILLED HER BASIN FROM THE CANAL LAST NIGHT BEFORE SHE WENT TO SLEEP, PREFERRING THE BRACKISH WATER TO THE SLIMY GREEN RAINWATER STEWING IN THE CISTERN OUT BACK. DIPPING A ROUGH CLOTH, SHE WASHED HERSELF HEAD TO HEEL, STANDING ON ONE LEG AT A TIME TO SCRUB HER CALLOUSED FEET. AFTER THAT SHE FOUND HER RAZOR. A BARE SCALP HELPED THE WIGS FIT BETTER, IZEMBARO CLAIMED.

SHE SHAVED, DONNED HER SMALLCLOTHES, AND SLIPPED A SHAPELESS BROWN WOOL DRESS DOWN OVER HER HEAD. ONE OF HER STOCKINGS NEEDED MENDING, SHE SAW AS SHE PULLED IT UP. SHE WOULD ASK THE SNAPPER FOR HELP; HER OWN SEWING WAS SO WRETCHED THAT THE WARDROBE MISTRESS USUALLY TOOK PITY ON HER. ELSE I COULD FILTCH A NICER PAIR FROM WARDROBE. THAT WAS RISKY, THOUGH. IZEMBARO HATED IT WHEN THE MUMMERS WORE HIS COSTUMES IN THE STREETS. EXCEPT FOR WENDEYNE. GIVE IZEMBARO’S COCK A LITTLE SUCK AND A GIRL CAN WEAR ANY COSTUME THAT SHE WANTS. MERCY WAS NOT SO FOOLISH AS ALL THAT. DAENA HAD WARNED HER. “GIRLS WHO START DOWN THAT ROAD WIND UP ON THE SHIP, WHERE EVERY MAN IN THE PIT KNOWS HE CAN HAVE ANY PRETTY THING HE MIGHT SEE UP ON THE STAGE, IF HIS PURSE IS PLUMP ENOUGH.”

HER BOOTS WERE LUMPS OF OLD BROWN LEATHER MOTTLED WITH SALTSTAINS AND CRACKED FROM LONG WEAR, HER BELT A LENGTH OF HEMPEN ROPE DYED BLUE. SHE KNOTTED IT ABOUT HER WAIST, AND HUNG A KNIFE ON HER RIGHT HIP AND A COIN POUCH ON HER LEFT. LAST OF ALL SHE THREW HER CLOAK ACROSS HER SHOULDERS. IT WAS A REAL MUMMER’S CLOAK, PURPLE WOOL LINED IN RED SILK, WITH A HOOD TO KEEP THE RAIN OFF, AND THREE SECRET POCKETS TOO. SHE’D HID SOME COINS IN ONE OF THOSE, AN IRON KEY IN ANOTHER, A BLADE IN THE LAST. A REAL BLADE, NOT A FRUIT KNIFE LIKE THE ONE ON HER HIP, BUT IT DID NOT BELONG TO MERCY, NO MORE THAN HER OTHER TREASURES DID. THE FRUIT KNIFE BELONGED TO MERCY. SHE WAS MADE FOR EATING FRUIT, FOR SMILING AND JOKING, FOR WORKING HARD AND DOING AS SHE WAS TOLD.

“MERCY, MERCY, MERCY,” SHE SANG AS SHE DESCENDED THE WOODEN STAIR TO THE STREET. THE HANDRAIL WAS SPLINTERY, THE STEPS STEEP, AND THERE WERE FIVE FLIGHTS, BUT THAT WAS WHY SHE’D GOTTEN THE ROOM SO CHEAP. THAT, AND MERCY’S SMILE. SHE MIGHT BE BALD AND SKINNY, BUT MERCY HAD A PRETTY SMILE, AND A CERTAIN GRACE. EVEN IZEMBARO AGREED THAT SHE WAS GRACEFUL. SHE WAS NOT FAR FROM THE GATE AS THE CROWS FLIES, BUT FOR GIRLS WITH FEET INSTEAD OF WINGS THE WAY WAS LONGER. BRAAVOS WAS A CROOKED CITY. THE STREETS WERE CROOKED, THE ALLEYS WERE CROOKEDER, AND THE CANALS WERE CROOKEDEST OF ALL. MOST DAYS SHE PREFERRED TO GO THE LONG WAY, DOWN THE RAGMAN’S ROAD ALONG THE OUTER HARBOR, WHERE SHE HAD THE SEA BEFORE HER AND THE SKY ABOVE, AND A CLEAR VIEW ACROSS THE GREAT LAGOON TO THE ARSENAL AND THE PINEY SLOPES OF SELLAGORO’S SHIELD. SAILORS WOULD HAIL HER AS SHE PASSED THE DOCKS, CALLING DOWN FROM THE DECKS OF TARRY IBBENESE WHALERS AND BIG-BELLIED WESTEROSI COGS. MERCY COULD NOT ALWAYS UNDERSTAND THEIR WORDS, BUT SHE KNEW WHAT THEY WERE SAYING. SOMETIMES SHE WOULD SMILE BACK AND TELL THEM THEY COULD FIND HER AT THE GATE IF THEY HAD THE COIN.

THE LONG WAY ALSO TOOK HER ACROSS THE BRIDGE OF EYES WITH ITS CARVED STONE FACES. FROM THE TOP OF ITS SPAN, SHE COULD LOOK THROUGH THE ARCHES AND SEE ALL THE CITY: THE GREEN COPPER DOMES OF THE HALL OF TRUTH, THE MASTS RISING LIKE A FOREST FROM THE PURPLE HARBOR, THE TALL TOWERS OF THE MIGHTY, THE GOLDEN THUNDERBOLT TURNING ON ITS SPIRE ATOP THE SEALORD’S PALACE… EVEN THE TITAN’S BRONZE SHOULDERS, OFF ACROSS THE DARK GREEN WATERS. BUT THAT WAS ONLY WHEN THE SUN WAS SHINING DOWN ON BRAAVOS. IF THE FOG WAS THICK THERE WAS NOTHING TO SEE BUT GREY, SO TODAY MERCY CHOSE THE SHORTER ROUTE TO SAVE SOME WEAR ON HER POOR CRACKED BOOTS.

THE MISTS SEEMED TO PART BEFORE HER AND CLOSE UP AGAIN AS SHE PASSED. THE COBBLESTONES WERE WET AND SLICK UNDER HER FEET. SHE HEARD A CAT YOWL PLAINTIVELY. BRAAVOS WAS A GOOD CITY FOR CATS, AND THEY ROAMED EVERYWHERE, ESPECIALLY AT NIGHT. IN THE FOG ALL CATS ARE GREY, MERCY THOUGHT. IN THE FOG ALL MEN ARE KILLERS.

SHE HAD NEVER SEEN A THICKER FOG THAN THIS ONE. ON THE LARGER CANALS, THE WATERMEN WOULD BE RUNNING THEIR SERPENT BOATS INTO ONE ANOTHER, UNABLE TO MAKE OUT ANY MORE THAN DIM LIGHTS FROM THE BUILDINGS TO EITHER SIDE OF THEM.

MERCY PASSED AN OLD MAN WITH A LANTERN WALKING THE OTHER WAY, AND ENVIED HIM HIS LIGHT. THE STREET WAS SO GLOOMY SHE COULD SCARCELY SEE WHERE SHE WAS STEPPING. IN THE HUMBLER PARTS OF THE CITY, THE HOUSES, SHOPS, AND WAREHOUSES CROWDED TOGETHER, LEANING ON EACH OTHER LIKE DRUNKEN LOVERS, THEIR UPPER STORIES SO CLOSE THAT YOU COULD STEP FROM ONE BALCONY TO THE NEXT. THE STREETS BELOW BECAME DARK TUNNELS WHERE EVERY FOOTFALL ECHOED. THE SMALL CANALS WERE EVEN MORE HAZARDOUS, SINCE MANY OF THE HOUSES THAT LINED THEM HAD PRIVIES JUTTING OUT OVER THE WATER. IZEMBARO LOVED TO GIVE THE SEALORD’S SPEECH FROM THE MERCHANT’S MELANCHOLY DAUGHTER, ABOUT HOW “HERE THE LAST TITAN YET STANDS, ASTRIDE THE STONY SHOULDERS OF HIS BROTHERS,” BUT MERCY PREFERRED THE SCENE WHERE THE FAT MERCHANT SHAT ON THE SEALORD’S HEAD AS HE PASSED UNDERNEATH IN HIS GOLD-AND-PURPLE BARGE. ONLY IN BRAAVOS COULD SOMETHING LIKE THAT HAPPEN, IT WAS SAID, AND ONLY IN BRAAVOS WOULD SEALORD AND SAILOR ALIKE HOWL WITH LAUGHTER TO SEE IT.

THE GATE STOOD CLOSE BY THE EDGE OF DROWNED TOWN, BETWEEN THE OUTER HARBOR AND THE PURPLE HARBOR. AN OLD WAREHOUSE HAD BURNT THERE AND THE GROUND WAS SINKING A LITTLE MORE EACH YEAR, SO THE LAND CAME CHEAP. ATOP THE FLOODED STONE FOUNDATION OF THE WAREHOUSE, IZEMBARO RAISED HIS CAVERNOUS PLAYHALL. THE DOME AND THE BLUE LANTERN MIGHT ENJOY MORE FASHIONABLE ENVIRONS, HE TOLD HIS MUMMERS, BUT HERE BETWEEN THE HARBORS THEY WOULD NEVER LACK FOR SAILORS AND WHORES TO FILL THEIR PIT. THE SHIP WAS CLOSE BY, STILL PULLING HANDSOME CROWDS TO THE QUAY WHERE SHE HAD BEEN MOORED FOR TWENTY YEARS, HE SAID, AND THE GATE WOULD FLOURISH TOO.

TIME HAD PROVED HIM RIGHT. THE GATE’S STAGE HAD DEVELOPED A TILT AS THE BUILDING SETTLED, THEIR COSTUMES WERE PRONE TO MILDEW, AND WATER SNAKES NESTED IN THE FLOODED CELLAR, BUT NONE OF THAT TROUBLED THE MUMMERS SO LONG AS THE HOUSE WAS FULL.

THE LAST BRIDGE WAS MADE OF ROPE AND RAW PLANKS, AND SEEMED TO DISSOLVE INTO NOTHINGNESS, BUT THAT WAS ONLY THE FOG. MERCY SCAMPERED ACROSS, HER HEELS RINGING ON THE WOOD. THE FOG OPENED BEFORE HER LIKE A TATTERED GREY CURTAIN TO REVEAL THE PLAYHOUSE. BUTTERY YELLOW LIGHT SPILLED FROM THE DOORS, AND MERCY COULD HEAR VOICES FROM WITHIN. BESIDE THE ENTRANCE, BIG BRUSCO HAD PAINTED OVER THE TITLE OF THE LAST SHOW, AND WRITTEN THE BLOODY HAND IN ITS PLACE IN HUGE RED LETTERS. HE WAS PAINTING A BLOODY HAND BENEATH THE WORDS, FOR THOSE WHO COULD NOT READ. MERCY STOPPED TO HAVE A LOOK. “THAT’S A NICE HAND,” SHE TOLD HIM.

“THUMB’S CROOKED.” BRUSCO DABBED AT IT WITH HIS BRUSH. “KING O’ THE MUMMERS BEEN ASKING AFTER YOU.”

“IT WAS SO DARK I SLEPT AND SLEPT.” WHEN IZEMBARO HAD FIRST DUBBED HIMSELF THE KING OF THE MUMMERS, THE COMPANY HAD TAKEN A WICKED PLEASURE IN IT, SAVORING THE OUTRAGE OF THEIR RIVALS FROM THE DOME AND THE BLUE LANTERN. OF LATE, THOUGH, IZEMBARO HAD BEGUN TO TAKE HIS TITLE TOO SERIOUSLY. “HE WILL ONLY PLAY KINGS NOW,” MARRO SAID, ROLLING HIS EYES, “AND IF THE PLAY HAS NO KING IN IT, HE WOULD SOONER NOT STAGE IT AT ALL.”

THE BLOODY HAND OFFERED TWO KINGS, THE FAT ONE AND THE BOY. IZEMBARO WOULD PLAY THE FAT ONE. IT WAS NOT A LARGE PART, BUT HE HAD A FINE SPEECH AS HE LAY DYING, AND A SPLENDID FIGHT WITH A DEMONIC BOAR BEFORE THAT. PHARIO FOREL HAD WRITTEN IT, AND HE HAD THE BLOODIEST QUILL OF ALL OF BRAAVOS.

MERCY FOUND THE COMPANY ASSEMBLED BEHIND THE STAGE, AND SLIPPED IN BETWEEN DAENA AND THE SNAPPER AT THE BACK, HOPING HER LATE ARRIVAL WOULD GO UNNOTICED. IZEMBARO WAS TELLING EVERYONE THAT HE EXPECTED THE GATE TO BE PACKED TO THE RAFTERS THIS EVENING, DESPITE THE FOG. “THE KING OF WESTEROS IS SENDING HIS ENVOY TO DO HOMAGE TO THE KING OF THE MUMMERS TONIGHT,” HE TOLD HIS TROUPE. “WE WILL NOT DISAPPOINT OUR FELLOW MONARCH.”

“WE?” SAID THE SNAPPER, WHO DID ALL THE COSTUMES FOR THE MUMMERS. “IS THERE MORE THAN ONE OF HIM, NOW?”

“HE’S FAT ENOUGH TO COUNT FOR TWO,” WHISPERED BOBONO. EVERY MUMMER’S TROUPE HAD TO HAVE A DWARF. HE WAS THEIRS. WHEN HE SAW MERCY, HE GAVE HER A LEER. “OHO,” HE SAID, “THERE SHE IS. IS THE LITTLE GIRL ALL READY FOR HER RAPE?” HE SMACKED HIS LIPS.

THE SNAPPER SMACKED HIM IN THE HEAD. “BE QUIET.”

THE KING OF THE MUMMERS IGNORED THE BRIEF COMMOTION. HE WAS STILL TALKING, TELLING THE MUMMERS HOW MAGNIFICENT THEY MUST BE. BESIDES THE WESTEROSI ENVOY, THERE WOULD BE KEYHOLDERS IN THE CROWD THIS EVENING, AND FAMOUS COURTESANS AS WELL. HE DID NOT INTEND FOR THEM TO LEAVE WITH A POOR OPINION OF THE GATE. “IT SHALL GO ILL FOR ANY MAN WHO FAILS ME,” HE PROMISED, A THREAT HE BORROWED FROM THE SPEECH PRINCE GARIN GIVES ON THE EVE OF BATTLE IN WROTH OF THE DRAGONLORDS, PHARIO FOREL’S FIRST PLAY.

BY THE TIME IZEMBARO FINALLY FINISHED SPEAKING, LESS THAN AN HOUR REMAINED BEFORE THE SHOW, AND THE MUMMERS WERE ALL FRANTIC AND FRETFUL BY TURNS. THE GATE RANG TO THE SOUND OF MERCY’S NAME.

“MERCY,” HER FRIEND DAENA IMPLORED, “LADY STORK HAS STEPPED ON THE HEM OF HER GOWN AGAIN. COME HELP ME SEW IT UP.”

“MERCY,” THE STRANGER CALLED, “BRING THE BLOODY PASTE, MY HORN IS COMING LOOSE.”

“MERCY,” BOOMED IZEMBARO THE GREAT HIMSELF, “WHAT HAVE YOU DONE WITH MY CROWN, GIRL? I CANNOT MAKE MY ENTRANCE WITHOUT MY CROWN. HOW SHALL THEY KNOW THAT I’M A KING?”

“MERCY,” SQUEAKED THE DWARF BOBONO, “MERCY, SOMETHING’S AMISS WITH MY LACES, MY COCK KEEPS FLOPPING OUT.”

SHE FETCHED THE STICKY PASTE AND FASTENED THE STRANGER’S LEFT HORN BACK ONTO HIS FOREHEAD. SHE FOUND IZEMBARO’S CROWN IN THE PRIVY WHERE HE ALWAYS LEFT IT AND HELPED HIM PIN IT TO HIS WIG, AND THEN RAN FOR NEEDLE AND THREAD SO THE SNAPPER COULD SEW THE LACE HEM BACK ONTO THE CLOTH-OF-GOLD GOWN THAT THE QUEEN WOULD WEAR IN THE WEDDING SCENE.

AND BOBONO’S COCK WAS INDEED FLOPPING OUT. IT WAS MADE TO FLOP OUT, FOR THE RAPE. WHAT A HIDEOUS THING, MERCY THOUGHT AS SHE KNELT BEFORE THE DWARF TO FIX HIM. THE COCK WAS A FOOT LONG AND AS THICK AS HER ARM, BIG ENOUGH TO BE SEEN FROM THE HIGHEST BALCONY. THE DYER HAD DONE A POOR JOB WITH THE LEATHER, THOUGH; THE THING WAS A MOTTLED PINK AND WHITE, WITH A BULBOUS HEAD THE COLOR OF A PLUM. MERCY PUSHED IT BACK INTO BOBONO’S BREECHES AND LACED HIM BACK UP. “MERCY,” HE SANG AS SHE TIED HIM TIGHT, “MERCY, MERCY, COME TO MY ROOM TONIGHT AND MAKE A MAN OF ME.”

“I’LL MAKE A EUNUCH OF YOU IF YOU KEEP UNLACING YOURSELF JUST SO I’LL FIDDLE WITH YOUR CROTCH.”

“WE WERE MEANT TO BE TOGETHER, MERCY,” BOBONO INSISTED. “LOOK, WE’RE JUST THE SAME HEIGHT.”

“ONLY WHEN I’M ON MY KNEES. DO YOU REMEMBER YOUR FIRST LINE?” IT HAD ONLY BEEN A FORTNIGHT SINCE THE DWARF HAD LURCHED ONTO STAGE IN HIS CUPS AND OPENED THE ANGUISH OF THE ARCHON WITH THE GRUMPKIN’S SPEECH FROM THE MERCHANT’S LUSTY LADY. IZEMBARO WOULD SKIN HIM ALIVE IF HE MADE SUCH A BLUNDER AGAIN, AND NEVER MIND HOW HARD IT WAS TO FIND A GOOD DWARF.

“WHAT ARE WE PLAYING, MERCY?” BOBONO ASKED INNOCENTLY.

HE IS TEASING ME, MERCY THOUGHT. HE’S NOT DRUNK TONIGHT, HE KNOWS THE SHOW PERFECTLY WELL. “WE ARE DOING PHARIO’S NEW BLOODY HAND, IN HONOR OF THE ENVOY FROM THE SEVEN KINGDOMS.”

“NOW I RECALL.” BOBONO LOWERED HIS VOICE TO A SINISTER CROAK. “THE SEVEN-FACED GOD HAS CHEATED ME,” HE SAID. “MY NOBLE SIRE HE MADE OF PUREST GOLD, AND GOLD HE MADE MY SIBLINGS, BOY AND GIRL. BUT I AM FORMED OF DARKER STUFF, OF BONES AND BLOOD AND CLAY, TWISTED INTO THIS RUDE SHAPE YOU SEE BEFORE YOU.” WITH THAT, HE GRABBED AT HER CHEST, FUMBLING FOR A NIPPLE. “YOU HAVE NO TITTIES. HOW CAN I RAPE A GIRL WITH NO TITTIES?”

SHE CAUGHT HIS NOSE BETWEEN HER THUMB AND FOREFINGER AND TWISTED. “YOU’LL HAVE NO NOSE UNTIL YOU GET YOUR HANDS OFF ME.”

“OWWWWW,” THE DWARF SQUEALED, RELEASING HER.

“I’LL GROW TITTIES IN A YEAR OR TWO.” MERCY ROSE, TO TOWER OVER THE LITTLE MAN. “BUT YOU’LL NEVER GROW ANOTHER NOSE. YOU THINK OF THAT, BEFORE YOU TOUCH ME THERE.”

BOBONO RUBBED HIS TENDER NOSE. “THERE’S NO NEED TO GET SO SHY. I’LL BE RAPING YOU SOON ENOUGH.”

“NOT UNTIL THE SECOND ACT.”

“I ALWAYS GIVE WENDEYNE’S TITTIES A NICE SQUEEZE WHEN I RAPE HER IN THE ANGUISH OF THE ARCHON,” THE DWARF COMPLAINED. “SHE LIKES IT, AND THE PIT DOES TOO. YOU HAVE TO PLEASE THE PIT.”

THAT WAS ONE OF IZEMBARO’S “WISDOMS,” AS HE LIKED TO CALL THEM. YOU HAVE TO PLEASE THE PIT. “I BET IT WOULD PLEASE THE PIT IF I RIPPED OFF THE DWARF’S COCK AND BEAT HIM ABOUT THE HEAD WITH IT,” MERCY REPLIED. “THAT’S SOMETHING THEY WON’T HAVE SEEN BEFORE.” ALWAYS GIVE THEM SOMETHING THEY HAVEN’T SEEN BEFORE WAS ANOTHER OF IZEMBARO’S “WISDOMS,” AND ONE THAT BOBONO HAD NO EASY ANSWER FOR. “THERE, YOU’RE DONE,” MERCY ANNOUNCED. “NOW SEE IF YOU CAN KEEP IN YOUR BREECHES TILL IT’S NEEDED.”

IZEMBARO WAS CALLING FOR HER AGAIN. NOW HE COULD NOT FIND HIS BOAR SPEAR. MERCY FOUND IT FOR HIM, HELPED BIG BRUSCO DON HIS BOAR SUIT, CHECKED THE TRICK DAGGERS JUST TO MAKE CERTAIN NO ONE HAD REPLACED ONE WITH A REAL BLADE (SOMEONE HAD DONE THAT AT THE DOME ONCE, AND A MUMMER HAD DIED), AND POURED LADY STORK THE LITTLE NIP OF WINE SHE LIKED TO HAVE BEFORE EACH PLAY. WHEN ALL THE CRIES OF “MERCY, MERCY, MERCY” FINALLY DIED AWAY, SHE STOLE A MOMENT FOR A QUICK PEEK OUT INTO THE HOUSE.

THE PIT WAS AS FULL AS EVER SHE’D SEEN IT, AND THEY WERE ENJOYING THEMSELVES ALREADY, JOKING AND JOSTLING, EATING AND DRINKING. SHE SAW A PEDDLER SELLING CHUNKS OF CHEESE, RIPPING THEM OFF THE WHEEL WITH HIS FINGERS WHENEVER HE FOUND A BUYER. A WOMAN HAD A BAG OF WRINKLED APPLES. SKINS OF WINE WERE BEING PASSED FROM HAND TO HAND, SOME GIRLS WERE SELLING KISSES, AND ONE SAILOR WAS PLAYING THE SEA PIPES. THE SAD-EYED LITTLE MAN CALLED QUILL STOOD IN THE BACK, COME TO SEE WHAT HE COULD STEAL FOR ONE OF HIS OWN PLAYS. COSSOMO THE CONJURER HAD COME AS WELL, AND ON HIS ARM WAS YNA, THE ONE-EYED WHORE FROM THE HAPPY PORT, BUT MERCY COULD NOT KNOW THOSE TWO, AND THEY WOULD NOT KNOW MERCY. DAENA RECOGNIZED SOME GATE REGULARS IN THE CROWD, AND POINTED THEM OUT FOR HER; THE DYER DELLONO WITH HIS PINCHED WHITE FACE AND MOTTLED PURPLE HANDS, GALEO THE SAUSAGE-MAKER IN HIS GREASY LEATHER APRON, TALL TOMARRO WITH HIS PET RAT ON HIS SHOULDER. “TOMARRO BEST NOT LET GALEO SEE THAT RAT,” DAENA WARNED. “THAT’S THE ONLY MEAT HE PUTS IN THEM SAUSAGES, I HEAR.” MERCY COVERED HER MOUTH AND LAUGHED.

THE BALCONIES WERE FILLING TOO. THE FIRST AND THIRD LEVELS WERE FOR MERCHANTS AND CAPTAINS AND OTHER RESPECTABLE FOLK. THE BRAVOS PREFERRED THE FOURTH AND HIGHEST, WHERE THE SEATS WERE CHEAPEST. IT WAS A RIOT OF BRIGHT COLOR UP THERE, WHILE DOWN BELOW MORE SOMBER SHADES HELD SWAY. THE SECOND BALCONY WAS CUT UP INTO PRIVATE BOXES WHERE THE MIGHTY COULD COMPORT THEMSELVES IN COMFORT AND PRIVACY, SAFELY APART FROM THE VULGARITY ABOVE AND BELOW. THEY HAD THE BEST VIEW OF THE STAGE, AND SERVANTS TO BRING THEM FOOD, WINE, CUSHIONS, WHATEVER THEY MIGHT DESIRE. IT WAS RARE TO FIND THE SECOND BALCONY MORE THAN HALF FULL AT THE GATE; SUCH OF THE MIGHTY WHO RELISHED A NIGHT OF MUMMERY WERE MORE INCLINED TO VISIT THE DOME OR THE BLUE LANTERN, WHERE THE OFFERINGS WERE CONSIDERED SUBTLER AND MORE POETIC.

THIS NIGHT WAS DIFFERENT, THOUGH, NO DOUBT ON ACCOUNT OF THE WESTEROSI ENVOY. IN ONE BOX SAT THREE SCIONS OF OTHARYS, EACH ACCOMPANIED BY A FAMOUS COURTESAN; PRESTAYN SAT ALONE, A MAN SO ANCIENT THAT YOU WONDERED HOW HE EVER REACHED HIS SEAT; TORONE AND PRANELIS SHARED A BOX, AS THEY SHARED AN UNCOMFORTABLE ALLIANCE; THE THIRD SWORD WAS HOSTING A HALF-DOZEN FRIENDS.

“I COUNT FIVE KEYHOLDERS,” SAID DAENA.

“BESSARO IS SO FAT YOU OUGHT TO COUNT HIM TWICE,” MERCY REPLIED, GIGGLING. IZEMBARO HAD A BELLY ON HIM, BUT COMPARED TO BESSARO HE WAS AS LITHE AS A WILLOW. THE KEYHOLDER WAS SO BIG HE NEEDED A SPECIAL SEAT, THRICE THE SIZE OF A COMMON CHAIR.

“THEY’RE ALL FAT, THEM REYAANS,” DAENA SAID. “BELLIES AS BIG AS THEIR SHIPS. YOU SHOULD HAVE SEEN THE FATHER. HE MADE THIS ONE LOOK SMALL. ONE TIME HE WAS SUMMONED TO THE HALL OF TRUTH TO VOTE, BUT WHEN HE STEPPED ONTO HIS BARGE IT SANK.” SHE CLUTCHED MERCY BY THE ELBOW. “LOOK, THE SEALORD’S BOX.” THE SEALORD HAD NEVER VISITED THE GATE, BUT IZEMBARO NAMED A BOX FOR HIM ANYWAY, THE LARGEST AND MOST OPULENT IN THE HOUSE. “THAT MUST BE THE WESTEROSI ENVOY. HAVE YOU EVER SEEN SUCH CLOTHES ON AN OLD MAN? AND LOOK, HE’S BROUGHT THE BLACK PEARL!”

THE ENVOY WAS SLIGHT AND BALDING, WITH A FUNNY GREY WISP OF A BEARD GROWING FROM HIS CHIN. HIS CLOAK WAS YELLOW VELVET, AND HIS BREECHES. HIS DOUBLET WAS A BLUE SO BRIGHT IT ALMOST MADE MERCY’S EYES WATER. UPON HIS BREAST A SHIELD HAD BEEN EMBROIDERED IN YELLOW THREAD, AND ON THE SHIELD WAS A PROUD BLUE ROOSTER PICKED OUT IN LAPIS LAZULI. ONE OF HIS GUARDS HELPED HIM TO HIS SEAT, WHILE TWO OTHERS STOOD BEHIND HIM IN THE BACK OF THE BOX.

THE WOMAN WITH HIM COULD NOT HAVE BEEN MORE THAN A THIRD HIS AGE. SHE WAS SO LOVELY THAT THE LAMPS SEEMED TO BURN BRIGHTER WHEN SHE PASSED. SHE HAD DRESSED IN A LOW-CUT GOWN OF PALE YELLOW SILK, STARTLING AGAINST THE LIGHT BROWN OF HER SKIN. HER BLACK HAIR WAS BOUND UP IN A NET OF SPUN GOLD, AND A JET-AND-GOLD NECKLACE BRUSHED AGAINST THE TOP OF HER FULL BREASTS. AS THEY WATCHED, SHE LEANED CLOSE TO THE ENVOY AND WHISPERED SOMETHING IN HIS EAR THAT MADE HIM LAUGH. “THEY SHOULD CALL HER THE BROWN PEARL,” MERCY SAID TO DAENA. “SHE’S MORE BROWN THAN BLACK.”

“THE FIRST BLACK PEARL WAS BLACK AS A POT OF INK,” SAID DAENA. “SHE WAS A PIRATE QUEEN, FATHERED BY A SEALORD’S SON ON A PRINCESS FROM THE SUMMER ISLES. A DRAGON KING FROM WESTEROS TOOK HER FOR HIS LOVER.”

“I WOULD LIKE TO SEE A DRAGON,” MERCY SAID WISTFULLY. “WHY DOES THE ENVOY HAVE A CHICKEN ON HIS CHEST?”

DAENA HOWLED. “MERCY, DON’T YOU KNOW ANYTHING? IT’S HIS SIGGLE. IN THE SUNSET KINGDOMS ALL THE LORDS HAVE SIGGLES. SOME HAVE FLOWERS, SOME HAVE FISH, SOME HAVE BEARS AND ELKS AND OTHER THINGS. SEE, THE ENVOY’S GUARDS ARE WEARING LIONS.”

IT WAS TRUE. THERE WERE FOUR GUARDS; BIG, HARD-LOOKING MEN IN RINGMAIL, WITH HEAVY WESTEROSI LONGSWORDS SHEATHED AT THEIR HIPS. THEIR CRIMSON CLOAKS WERE BORDERED IN WHORLS OF GOLD, AND GOLDEN LIONS WITH RED GARNET EYES CLASPED EACH CLOAK AT THE SHOULDER. WHEN MERCY GLANCED AT THE FACES BENEATH THE GILDED, LION-CRESTED HELM, HER BELLY GAVE A QUIVER. THE GODS HAVE GIVEN ME A GIFT. HER FINGERS CLUTCHED HARD AT DAENA’S ARM. “THAT GUARD. THE ONE ON THE END, BEHIND THE BLACK PEARL.”

“WHAT OF HIM? DO YOU KNOW HIM?”

“NO.” MERCY HAD BEEN BORN AND BRED IN BRAAVOS, HOW COULD SHE KNOW SOME WESTEROSI? SHE HAD TO THINK A MOMENT. “IT’S ONLY… WELL, HE’S FAIR TO LOOK ON, DON’T YOU THINK?” HE WAS, IN A ROUGH-HEWN WAY, THOUGH HIS EYES WERE HARD.

DAENA SHRUGGED. “HE’S VERY OLD. NOT SO OLD AS THE OTHER ONES, BUT… HE COULD BE THIRTY. AND WESTEROSI. THEY’RE TERRIBLE SAVAGES, MERCY. BEST STAY WELL AWAY FROM HIS SORT.”

“STAY AWAY?” MERCY GIGGLED. SHE WAS A GIGGLY SORT OF GIRL, WAS MERCY. “NO. I’VE GOT TO GET CLOSER.” SHE GAVE DAENA A SQUEEZE AND SAID, “IF THE SNAPPER COMES LOOKING FOR ME, TELL HER THAT I WENT OFF TO READ MY LINES AGAIN.” SHE ONLY HAD A FEW, AND MOST WERE JUST, “OH, NO, NO, NO,” AND “DON’T, OH DON’T, DON’T TOUCH ME,” AND “PLEASE, M’LORD, I AM STILL A MAIDEN,” BUT THIS WAS THE FIRST TIME IZEMBARO HAD GIVEN HER ANY LINES AT ALL, SO IT WAS ONLY TO BE EXPECTED THAT POOR MERCY WOULD WANT TO GET THEM RIGHT.

THE ENVOY FROM THE SEVEN KINGDOMS HAD TAKEN TWO OF HIS GUARDS INTO HIS BOX TO STAND BEHIND HIM AND THE BLACK PEARL, BUT THE OTHER TWO HAD BEEN POSTED JUST OUTSIDE THE DOOR TO MAKE CERTAIN HE WAS NOT DISTURBED. THEY WERE TALKING QUIETLY IN THE COMMON TONGUE OF WESTEROS AS SHE SLIPPED UP SILENTLY BEHIND THEM IN THE DARKENED PASSAGE. THAT WAS NOT A LANGUAGE MERCY KNEW.

“SEVEN HELLS, THIS PLACE IS DAMP,” SHE HEARD HER GUARD COMPLAIN. “I’M CHILLED TO THE BONES. WHERE ARE THE BLOODY ORANGE TREES? I ALWAYS HEARD THERE WERE ORANGE TREES IN THE FREE CITIES. LEMONS AND LIMES. POMEGRANATES. HOT PEPPERS, WARM NIGHTS, GIRLS WITH BARE BELLIES. WHERE ARE THE BARE-BELLIED GIRLS, I ASK YOU?”

“DOWN IN LYS, AND MYR, AND OLD VOLANTIS,” THE OTHER GUARD REPLIED. HE WAS AN OLDER MAN, BIG-BELLIED AND GRIZZLED. “I WENT TO LYS WITH LORD TYWIN ONCE, WHEN HE WAS HAND TO AERYS. BRAAVOS IS NORTH OF KING’S LANDING, FOOL. CAN’T YOU READ A BLOODY MAP?”

“HOW LONG DO YOU THINK WE’LL BE HERE?”

“LONGER THAN YOU’D LIKE,” THE OLD MAN REPLIED. “IF HE GOES BACK WITHOUT THE GOLD THE QUEEN WILL HAVE HIS HEAD. BESIDES, I SEEN THAT WIFE OF HIS. THERE’S STEPS IN CASTERLY ROCK SHE CAN’T GO DOWN FOR FEAR SHE’D GET STUCK, THAT’S HOW FAT SHE IS. WHO’D GO BACK TO THAT, WHEN HE HAS HIS SOOTY QUEEN?”

THE HANDSOME GUARDSMAN GRINNED. “DON’T SUPPOSE HE’LL SHARE HER WITH US, AFTERWARD?”

“WHAT, ARE YOU MAD? YOU THINK HE NOTICES THE LIKES OF US? BLOODY BUGGER DON’T EVEN GET OUR NAMES RIGHT HALF THE TIME. MAYBE IT WAS DIFFERENT WITH CLEGANE.”

“SER WASN’T ONE FOR MUMMER SHOWS AND FANCY WHORES. WHEN SER WANTED A WOMAN HE TOOK ONE, BUT SOMETIMES HE’D LET US HAVE HER, AFTER. I WOULDN’T MIND HAVING A TASTE OF THAT BLACK PEARL. YOU THINK SHE’S PINK BETWEEN HER LEGS?”

MERCY WANTED TO HEAR MORE, BUT THERE WAS NO TIME. THE BLOODY HAND WAS ABOUT TO START, AND THE SNAPPER WOULD BE LOOKING FOR HER TO HELP WITH COSTUMES. IZEMBARO MIGHT BE THE KING OF THE MUMMERS, BUT THE SNAPPER WAS THE ONE THAT THEY ALL FEARED. TIME ENOUGH FOR HER PRETTY GUARDSMAN LATER.

THE BLOODY HAND OPENED IN A LICHYARD.

WHEN THE DWARF APPEARED SUDDENLY FROM BEHIND A WOODEN TOMBSTONE, THE CROWD BEGAN TO HISS AND CURSE. BOBONO WADDLED TO THE FRONT OF THE STAGE AND LEERED AT THEM. “THE SEVEN-FACED GOD HAS CHEATED ME,” HE BEGAN, SNARLING THE WORDS. “MY NOBLE SIRE HE MADE OF PUREST GOLD, AND GOLD HE MADE MY SIBLINGS, BOY AND GIRL. BUT I AM FORMED OF DARKER STUFF, OF BONES AND BLOOD AND CLAY… “

BY THEN MARRO HAD APPEARED BEHIND HIM, GAUNT AND TERRIBLE IN THE STRANGER’S LONG BLACK ROBES. HIS FACE WAS BLACK AS WELL, HIS TEETH RED AND SHINY WITH BLOOD, WHILE IVORY HORNS JUTTED UPWARDS FROM HIS BROW. BOBONO COULD NOT SEE HIM, BUT THE BALCONIES COULD, AND NOW THE PIT AS WELL. THE GATE GREW DEATHLY QUIET. MARRO MOVED FORWARD SILENTLY.

SO DID MERCY. THE COSTUMES WERE ALL HUNG, AND THE SNAPPER WAS BUSY SEWING DAENA INTO HER GOWN FOR THE COURT SCENE, SO MERCY’S ABSENCE SHOULD NOT BE NOTED. QUIET AS A SHADOW, SHE SLIPPED AROUND THE BACK AGAIN, UP TO WHERE THE GUARDSMEN STOOD OUTSIDE THE ENVOY’S BOX. STANDING IN A DARKENED ALCOVE, STILL AS STONE, SHE HAD A GOOD LOOK AT HIS FACE. SHE STUDIED IT CAREFULLY, TO BE SURE. AM I TOO YOUNG FOR HIM? SHE WONDERED. TOO PLAIN? TOO SKINNY? SHE HOPED HE WASN’T THE SORT OF MAN WHO LIKED BIG BREASTS ON A GIRL. BOBONO HAD BEEN RIGHT ABOUT HER CHEST. IT WOULD BE BEST IF I COULD TAKE HIM BACK TO MY PLACE, HAVE HIM ALL TO MYSELF. BUT WILL HE COME WITH ME?

“YOU THINK IT MIGHT BE HIM?” THE PRETTY ONE WAS SAYING.

“WHAT, DID THE OTHERS TAKE YOUR WITS?”

“WHY NOT? HE’S A DWARF, AIN’T HE?”

“THE IMP WEREN’T THE ONLY DWARF IN THE WORLD.”

“MAYBE NOT, BUT LOOK HERE, EVERYONE SAYS HOW CLEVER HE WAS, TRUE? SO MAYBE HE FIGURES THE LAST PLACE HIS SISTER WOULD EVER LOOK FOR HIM WOULD BE IN SOME MUMMER SHOW, MAKING FUN OF HIMSELF. SO HE DOES JUST THAT, TO TWEAK HER NOSE.”

“AH, YOU’RE MAD.”

“WELL, MAYBE I’LL FOLLOW HIM AFTER THE MUMMERY. FIND OUT FOR MYSELF.” THE GUARDSMAN PUT A HAND ON THE HILT OF HIS SWORD. “IF I’M RIGHT, I’LL BE A MA LORD, AND IF I’M WRONG, WELL, BLEED IT, IT’S JUST SOME DWARF.” HE GAVE A BARK OF LAUGHTER.

ON STAGE, BOBONO WAS BARGAINING WITH MARRO’S SINISTER STRANGER. HE HAD A BIG VOICE FOR SUCH A LITTLE MAN, AND HE MADE IT RING OFF THE HIGHEST RAFTERS NOW. “GIVE ME THE CUP,” HE TOLD THE STRANGER, “FOR I SHALL DRINK DEEP. AND IF IT TASTES OF GOLD AND LION’S BLOOD, SO MUCH THE BETTER. AS I CANNOT BE THE HERO, LET ME BE THE MONSTER, AND LESSON THEM IN FEAR IN PLACE OF LOVE.”

MERCY MOUTHED THE LAST LINES ALONG WITH HIM. THEY WERE BETTER LINES THAN HERS, AND APT BESIDES. HE’LL WANT ME OR HE WON’T, SHE THOUGHT, SO LET THE PLAY BEGIN. SHE SAID A SILENT PRAYER TO THE GOD OF MANY FACES, SLIPPED OUT OF HER ALCOVE, AND FLOUNCED UP TO THE GUARDSMEN. MERCY, MERCY, MERCY. “MY LORDS,” SHE SAID, “DO YOU SPEAK BRAAVOSI? OH, PLEASE, TELL ME YOU DO.”

THE TWO GUARDSMEN EXCHANGED A LOOK. “WHAT’S THIS THING GOING ON ABOUT?” THE OLDER ONE ASKED. “WHO IS SHE?”

“ONE OF THE MUMMERS,” SAID THE PRETTY ONE. HE PUSHED HIS FAIR HAIR BACK OFF HIS BROW AND SMILED AT HER. “SORRY, SWEETLING, WE DON’T SPEAK YOUR GIBBLE-GABBLE.”

FUSS AND FEATHERS, MERCY THOUGHT, THEY ONLY KNOW THE COMMON TONGUE. THAT WAS NO GOOD. GIVE IT UP OR GO AHEAD. SHE COULD NOT GIVE IT UP. SHE WANTED HIM SO BAD. “I KNOW YOUR TONGUE, A LITTLE,” SHE LIED, WITH MERCY’S SWEETEST SMILE. “YOU ARE LORDS OF WESTEROS, MY FRIEND SAID.”

THE OLD ONE LAUGHED. “LORDS? AYE, THAT’S US.”

MERCY LOOKED DOWN AT HER FEET, SO SHY. “IZEMBARO SAID TO PLEASE THE LORDS,” SHE WHISPERED. “IF THERE IS ANYTHING YOU WANT, ANYTHING AT ALL… “

THE TWO GUARDSMEN EXCHANGED A LOOK. THEN THE HANDSOME ONE REACHED OUT AND TOUCHED HER BREAST. “ANYTHING?“

“YOU’RE DISGUSTING,” SAID THE OLDER MAN.

“WHY? IF THIS IZEMBARO WANTS TO BE HOSPITABLE, IT WOULD BE RUDE TO REFUSE.” HE GAVE HER NIPPLE A TWEAK THROUGH THE FABRIC OF HER DRESS, JUST THE WAY THE DWARF HAD DONE WHEN SHE WAS FIXING HIS COCK FOR HIM. “MUMMERS ARE THE NEXT BEST THING TO WHORES.”

“MIGHT BE, BUT THIS ONE IS A CHILD.”

“I AM NOT,” LIED MERCY. “I’M A MAIDEN NOW.”

“NOT FOR LONG,” SAID THE COMELY ONE. “I’M LORD RAFFORD, SWEETLING, AND I KNOW JUST WHAT I WANT. HIKE UP THOSE SKIRTS NOW, AND LEAN BACK AGAINST THAT WALL.”

“NOT HERE,” MERCY SAID, BRUSHING HIS HANDS AWAY. “NOT WHERE THE PLAY IS ON. I MIGHT CRY OUT, AND IZEMBARO WOULD BE MAD.”

“WHERE, THEN?”

“I KNOW A PLACE.”

THE OLDER GUARD WAS SCOWLING. “WHAT, YOU THINK CAN JUST SCAMPER OFF? WHAT IF HIS KNIGHTLINESS COMES LOOKING FOR YOU?”

“WHY WOULD HE? HE’S GOT A SHOW TO WATCH. AND HE’S GOT HIS OWN WHORE, WHY SHOULDN’T I HAVE MINE? THIS WON’T TAKE LONG.”

NO, SHE THOUGHT, IT WON’T. MERCY TOOK HIM BY THE HAND, LED HIM THROUGH THE BACK AND DOWN THE STEPS AND OUT INTO THE FOGGY NIGHT. “YOU COULD BE A MUMMER, IF YOU WANTED,” SHE TOLD HIM, AS HE PRESSED HER UP AGAINST THE WALL OF THE PLAYHOUSE.

“ME?” THE GUARDSMAN SNORTED. “NOT ME, GIRL. ALL THAT BLOODY TALKING, I WOULDN’T REMEMBER HALF OF IT.”

“IT’S HARD AT FIRST,” SHE ADMITTED. “BUT AFTER A TIME IT COMES EASIER. I COULD TEACH YOU TO SAY A LINE. I COULD.”

HE GRABBED HER WRIST. “I’LL DO THE TEACHING. TIME FOR YOUR FIRST LESSON.” HE PULLED HER HARD AGAINST HIM AND KISSED HER ON THE LIPS, FORCING HIS TONGUE INTO HER MOUTH. IT WAS ALL WET AND SLIMY, LIKE AN EEL. MERCY LICKED IT WITH HER OWN TONGUE, THEN BROKE AWAY FROM HIM, BREATHLESS. “NOT HERE. SOMEONE MIGHT SEE. MY ROOM’S NOT FAR, BUT HURRY. I HAVE TO BE BACK BEFORE THE SECOND ACT, OR I’LL MISS MY RAPE.”

HE GRINNED. “NO FEAR O’ THAT, GIRL.” BUT HE LET HER PULL HIM AFTER HER. HAND IN HAND, THEY WENT RACING THROUGH THE FOG, OVER BRIDGES AND THROUGH ALLEYS AND UP FIVE FLIGHTS OF SPLINTERY WOODEN STAIRS. THE GUARDSMAN WAS PANTING BY THE TIME THEY BURST THROUGH THE DOOR OF HER LITTLE ROOM. MERCY LIT A TALLOW CANDLE, THEN DANCED AROUND AT HIM, GIGGLING. “OH, NOW YOU’RE ALL TIRED OUT. I FORGOT HOW OLD YOU WERE, M’LORD. DO YOU WANT TO TAKE A LITTLE NAP? JUST LIE DOWN AND CLOSE YOUR EYES, AND I’LL COME BACK AFTER THE IMP’S DONE RAPING ME.”

“YOU’RE NOT GOING ANYWHERE.” HE PULLED HER ROUGHLY TO HIM. “GET THOSE RAGS OFF, AND I’LL SHOW YOU HOW OLD I AM, GIRL.”

“MERCY,” SHE SAID. “MY NAME IS MERCY. CAN YOU SAY IT?”

“MERCY,” HE SAID. “MY NAME IS RAFF.”

“I KNOW.” SHE SLIPPED HER HAND BETWEEN HIS LEGS, AND FELT HOW HARD HE WAS THROUGH THE WOOL OF HIS BREECHES.

“THE LACES,” HE URGED HER. “BE A SWEET GIRL AND UNDO THEM.” INSTEAD SHE SLID HER FINGER DOWN ALONG THE INSIDE OF HIS THIGH. HE GAVE A GRUNT. “DAMN, BE CAREFUL THERE, YOU — “

MERCY GAVE A GASP AND STEPPED AWAY, HER FACE CONFUSED AND FRIGHTENED. “YOU’RE BLEEDING.”

“WHA — ” HE LOOKED DOWN AT HIMSELF. “GODS BE GOOD. WHAT DID YOU DO TO ME, YOU LITTLE CUNT?” THE RED STAIN SPREAD ACROSS HIS THIGH, SOAKING THE HEAVY FABRIC.

“NOTHING,” MERCY SQUEAKED. “I NEVER… OH, OH, THERE’S SO MUCH BLOOD. STOP IT, STOP IT, YOU’RE SCARING ME.”

HE SHOOK HIS HEAD, A DAZED LOOK ON HIS FACE. WHEN HE PRESSED HIS HAND TO HIS THIGH, BLOOD SQUIRTED THROUGH HIS FINGERS. IT WAS RUNNING DOWN HIS LEG, INTO HIS BOOT. HE DOESN’T LOOK SO COMELY NOW, SHE THOUGHT. HE JUST LOOKS WHITE AND FRIGHTENED.

“A TOWEL,” THE GUARDSMAN GASPED. “BRING ME A TOWEL, A RAG, PRESS DOWN ON IT. GODS. I FEEL DIZZY.” HIS LEG WAS DRENCHED WITH BLOOD FROM THE THIGH DOWN. WHEN HE TRIED TO PUT HIS WEIGHT ON IT, HIS KNEE BUCKLED AND HE FELL. “HELP ME,” HE PLEADED, AS THE CROTCH OF HIS BREECHES REDDENED. “MOTHER HAVE MERCY, GIRL. A HEALER… RUN AND FIND A HEALER, QUICK NOW.”

“THERE’S ONE ON THE NEXT CANAL, BUT HE WON’T COME. YOU HAVE TO GO TO HIM. CAN’T YOU WALK?”

“WALK?” HIS FINGERS WERE SLICK WITH BLOOD. “ARE YOU BLIND, GIRL? I’M BLEEDING LIKE A STUCK PIG. I CAN’T WALK ON THIS.”

“WELL,” SHE SAID, “I DON’T KNOW HOW YOU’LL GET THERE, THEN.”

“YOU’LL NEED TO CARRY ME.”

SEE? THOUGHT MERCY. YOU KNOW YOUR LINE, AND SO DO I.

“THINK SO?” ASKED ARYA, SWEETLY.

RAFF THE SWEETLING LOOKED UP SHARPLY AS THE LONG THIN BLADE CAME SLIDING FROM HER SLEEVE. SHE SLIPPED IT THROUGH HIS THROAT BENEATH THE CHIN, TWISTED, AND RIPPED IT BACK OUT SIDEWAYS WITH A SINGLE SMOOTH SLASH. A FINE RED RAIN FOLLOWED, AND IN HIS EYES THE LIGHT WENT OUT.

“VALAR MORGHULIS,” ARYA WHISPERED, BUT RAFF WAS DEAD AND DID NOT HEAR. SHE SNIFFED. I SHOULD HAVE HELPED HIM DOWN THE STEPS BEFORE I KILLED HIM. NOW I’LL NEED TO DRAG HIM ALL THE WAY TO THE CANAL AND ROLL HIM IN. THE EELS WOULD DO THE REST.

“MERCY, MERCY, MERCY,” SHE SANG SADLY. A FOOLISH, GIDDY GIRL SHE’D BEEN, BUT GOOD HEARTED. SHE WOULD MISS HER, AND SHE WOULD MISS DAENA AND THE SNAPPER AND THE REST, EVEN IZEMBARO AND BOBONO. THIS WOULD MAKE TROUBLE FOR THE SEALORD AND THE ENVOY WITH THE CHICKEN ON HIS CHEST, SHE DID NOT DOUBT.

SHE WOULD THINK ABOUT THAT LATER, THOUGH. JUST NOW, THERE WAS NO TIME. I HAD BEST RUN. MERCY STILL HAD SOME LINES TO SAY, HER FIRST LINES AND HER LAST, AND IZEMBARO WOULD HAVE HER PRETTY LITTLE EMPTY HEAD IF SHE WERE LATE FOR HER OWN RAPE.
"

puts text.split(" ").map { |e| e.split("").reject {|e|!("ABCDEFGHIJKLMNOPQRSTUVWZYZ".chars.include?(e))}.join }.uniq.map { |e| "\"#{e}\"" }.join(",")