# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d0f714ad366a9ec12816ff742510d90710c5162eb78a9011e974dddbe8652cf0712acc0e2d8053bd9c6159088ae75ab90af1703decd4ac3d4a21702cb2e068b

test:
  secret_key_base: a055a175562380f72006e049de4f7bda0aea42b9a151d728007de29e0e2b0542fd09faf38349e4d407c030c78c223e5e6a7e12a97ce385cef1936b58da1f31ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
